#ConnectionString: server=(localdb)\DemoApplication;database=DemoApplicationDb
ConnectionString: server=(localdb)\ApplicationCore;database=ApplicationDb
BasePath:  fake path blah blah blah 
#BasePath: C:\Repos\Application\Core
#BasePath: C:\Repos\Application\Core2Duo
#BasePath: C:\Repos\Application\Demo
AssemblySearchPath: .\ApiServices\src\WebApi\bin\Debug\netcoreapp3.1
#AssemblySearchPath: .\ApiServices\src\WebApi\bin\Debug\net6.0
UserSession:
  UserId: DDE27BBD-5647-4611-B662-088C7FBA3E55
  Username: SystemUser
Contexts:
- OoBDev.Core.Persistence.CoreDbContext, OoBDev.Core.Persistence
#- OoBDev.Core.AnnouncementBanners.Persistence.CoreBannersDbContext, OoBDev.Core.AnnouncementBanners
#- OoBDev.Core.ClaimScopes.Persistence.CoreClaimScopesDbContext, OoBDev.Core.ClaimScopes
#- OoBDev.Core.APP.Persistence.CMSDbContext, OoBDev.Core.CMS
#- OoBDev.Core.DynamicForms.Persistence.DynamicFormsDbContext, OoBDev.Core.DynamicForms
#- OoBDev.Core.Languages.Persistence.CoreLanguagesDbContext, OoBDev.Core.Languages
SourceDataPaths:
- .\conf\dataLoading\config-base
- .\conf\dataLoading\config-demoSet1
- .\conf\dataLoading\transaction-demoSet1
DuplicateHandling: First # Fail|First|Last
#ImportMasterData: Last # First|Skip|Last
#DisableForeignKeysBeforeInsert: true  # true|false
