ALTER TABLE [Logging].[Sessions]
    ADD CONSTRAINT [PK_Sessions] PRIMARY KEY CLUSTERED ([SessionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

