ALTER TABLE [Security].[UsersInRoles]
    ADD CONSTRAINT [PK_UsersInRoles] PRIMARY KEY CLUSTERED ([UserID] ASC, [RoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

