ALTER TABLE [dbo].[Forms]
    ADD CONSTRAINT [PK_Forms] PRIMARY KEY CLUSTERED ([FormID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

