<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="Handlebars.Net.Helpers" Version="2.4.5" />
    <PackageReference Include="Handlebars.Net.Helpers.Humanizer" Version="2.4.5" />
    <PackageReference Include="OllamaSharp" Version="2.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Prompts\Angular2React.md.hbs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\GenerateUnitTests.md.hbs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\GenerateDocumentationForThisCode.md.hbs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
