FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KEYCLOAK_IMPORT=local-dev-realm.json
ENV KEYCLOAK_SCRIPT_UPLOAD_ENABLED=true

# Copy the import file to the appropriate directory
COPY ./keycloak/${KEYCLOAK_IMPORT} /opt/keycloak/data/import/

# Expose the necessary port
EXPOSE 8080

# Use ENTRYPOINT and CMD to ensure the environment variables are passed correctly
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
CMD ["--import-realm", "--script-upload-enabled=true"]
