#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.Data.CarMonitor
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarMonitor")]
	public partial class CarMonitorDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCar(Car instance);
    partial void UpdateCar(Car instance);
    partial void DeleteCar(Car instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertInsurancePolicy(InsurancePolicy instance);
    partial void UpdateInsurancePolicy(InsurancePolicy instance);
    partial void DeleteInsurancePolicy(InsurancePolicy instance);
    partial void InsertInsurancePoliciesForCar(InsurancePoliciesForCar instance);
    partial void UpdateInsurancePoliciesForCar(InsurancePoliciesForCar instance);
    partial void DeleteInsurancePoliciesForCar(InsurancePoliciesForCar instance);
    partial void InsertMaintenanceType(MaintenanceType instance);
    partial void UpdateMaintenanceType(MaintenanceType instance);
    partial void DeleteMaintenanceType(MaintenanceType instance);
    partial void InsertPaymentsCar(PaymentsCar instance);
    partial void UpdatePaymentsCar(PaymentsCar instance);
    partial void DeletePaymentsCar(PaymentsCar instance);
    partial void InsertPaymentsCarsFuel(PaymentsCarsFuel instance);
    partial void UpdatePaymentsCarsFuel(PaymentsCarsFuel instance);
    partial void DeletePaymentsCarsFuel(PaymentsCarsFuel instance);
    partial void InsertPaymentsCarsMaintenance(PaymentsCarsMaintenance instance);
    partial void UpdatePaymentsCarsMaintenance(PaymentsCarsMaintenance instance);
    partial void DeletePaymentsCarsMaintenance(PaymentsCarsMaintenance instance);
    partial void InsertPaymentsInsurancePolicy(PaymentsInsurancePolicy instance);
    partial void UpdatePaymentsInsurancePolicy(PaymentsInsurancePolicy instance);
    partial void DeletePaymentsInsurancePolicy(PaymentsInsurancePolicy instance);
    #endregion
		
		public CarMonitorDataDataContext() : 
				base(global::WhitedUS.Data.Properties.Settings.Default.CarMonitorConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarMonitorDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarMonitorDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarMonitorDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarMonitorDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Car> Cars
		{
			get
			{
				return this.GetTable<Car>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<InsurancePolicy> InsurancePolicies
		{
			get
			{
				return this.GetTable<InsurancePolicy>();
			}
		}
		
		public System.Data.Linq.Table<InsurancePoliciesForCar> InsurancePoliciesForCars
		{
			get
			{
				return this.GetTable<InsurancePoliciesForCar>();
			}
		}
		
		public System.Data.Linq.Table<MaintenanceType> MaintenanceTypes
		{
			get
			{
				return this.GetTable<MaintenanceType>();
			}
		}
		
		public System.Data.Linq.Table<PaymentsCar> PaymentsCars
		{
			get
			{
				return this.GetTable<PaymentsCar>();
			}
		}
		
		public System.Data.Linq.Table<PaymentsCarsFuel> PaymentsCarsFuels
		{
			get
			{
				return this.GetTable<PaymentsCarsFuel>();
			}
		}
		
		public System.Data.Linq.Table<PaymentsCarsMaintenance> PaymentsCarsMaintenances
		{
			get
			{
				return this.GetTable<PaymentsCarsMaintenance>();
			}
		}
		
		public System.Data.Linq.Table<PaymentsInsurancePolicy> PaymentsInsurancePolicies
		{
			get
			{
				return this.GetTable<PaymentsInsurancePolicy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cars")]
	public partial class Car : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CarID;
		
		private string _Name;
		
		private string _Make;
		
		private string _Model;
		
		private int _Year;
		
		private int _OwnerID;
		
		private EntitySet<InsurancePoliciesForCar> _InsurancePoliciesForCars;
		
		private EntitySet<PaymentsCar> _PaymentsCars;
		
		private EntitySet<PaymentsCarsFuel> _PaymentsCarsFuels;
		
		private EntitySet<PaymentsCarsMaintenance> _PaymentsCarsMaintenances;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarIDChanging(int value);
    partial void OnCarIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMakeChanging(string value);
    partial void OnMakeChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void OnOwnerIDChanging(int value);
    partial void OnOwnerIDChanged();
    #endregion
		
		public Car()
		{
			this._InsurancePoliciesForCars = new EntitySet<InsurancePoliciesForCar>(new Action<InsurancePoliciesForCar>(this.attach_InsurancePoliciesForCars), new Action<InsurancePoliciesForCar>(this.detach_InsurancePoliciesForCars));
			this._PaymentsCars = new EntitySet<PaymentsCar>(new Action<PaymentsCar>(this.attach_PaymentsCars), new Action<PaymentsCar>(this.detach_PaymentsCars));
			this._PaymentsCarsFuels = new EntitySet<PaymentsCarsFuel>(new Action<PaymentsCarsFuel>(this.attach_PaymentsCarsFuels), new Action<PaymentsCarsFuel>(this.detach_PaymentsCarsFuels));
			this._PaymentsCarsMaintenances = new EntitySet<PaymentsCarsMaintenance>(new Action<PaymentsCarsMaintenance>(this.attach_PaymentsCarsMaintenances), new Action<PaymentsCarsMaintenance>(this.detach_PaymentsCarsMaintenances));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					this.OnCarIDChanging(value);
					this.SendPropertyChanging();
					this._CarID = value;
					this.SendPropertyChanged("CarID");
					this.OnCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Make", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Make
		{
			get
			{
				return this._Make;
			}
			set
			{
				if ((this._Make != value))
				{
					this.OnMakeChanging(value);
					this.SendPropertyChanging();
					this._Make = value;
					this.SendPropertyChanged("Make");
					this.OnMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="Int NOT NULL")]
		public int OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOwnerIDChanging(value);
					this.SendPropertyChanging();
					this._OwnerID = value;
					this.SendPropertyChanged("OwnerID");
					this.OnOwnerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_InsurancePoliciesForCar", Storage="_InsurancePoliciesForCars", ThisKey="CarID", OtherKey="CarID")]
		public EntitySet<InsurancePoliciesForCar> InsurancePoliciesForCars
		{
			get
			{
				return this._InsurancePoliciesForCars;
			}
			set
			{
				this._InsurancePoliciesForCars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_PaymentsCar", Storage="_PaymentsCars", ThisKey="CarID", OtherKey="CarID")]
		public EntitySet<PaymentsCar> PaymentsCars
		{
			get
			{
				return this._PaymentsCars;
			}
			set
			{
				this._PaymentsCars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_PaymentsCarsFuel", Storage="_PaymentsCarsFuels", ThisKey="CarID", OtherKey="CarID")]
		public EntitySet<PaymentsCarsFuel> PaymentsCarsFuels
		{
			get
			{
				return this._PaymentsCarsFuels;
			}
			set
			{
				this._PaymentsCarsFuels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_PaymentsCarsMaintenance", Storage="_PaymentsCarsMaintenances", ThisKey="CarID", OtherKey="CarID")]
		public EntitySet<PaymentsCarsMaintenance> PaymentsCarsMaintenances
		{
			get
			{
				return this._PaymentsCarsMaintenances;
			}
			set
			{
				this._PaymentsCarsMaintenances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Car", Storage="_User", ThisKey="OwnerID", OtherKey="PersonID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Cars.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Cars.Add(this);
						this._OwnerID = value.PersonID;
					}
					else
					{
						this._OwnerID = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_InsurancePoliciesForCars(InsurancePoliciesForCar entity)
		{
			this.SendPropertyChanging();
			entity.Car = this;
		}
		
		private void detach_InsurancePoliciesForCars(InsurancePoliciesForCar entity)
		{
			this.SendPropertyChanging();
			entity.Car = null;
		}
		
		private void attach_PaymentsCars(PaymentsCar entity)
		{
			this.SendPropertyChanging();
			entity.Car = this;
		}
		
		private void detach_PaymentsCars(PaymentsCar entity)
		{
			this.SendPropertyChanging();
			entity.Car = null;
		}
		
		private void attach_PaymentsCarsFuels(PaymentsCarsFuel entity)
		{
			this.SendPropertyChanging();
			entity.Car = this;
		}
		
		private void detach_PaymentsCarsFuels(PaymentsCarsFuel entity)
		{
			this.SendPropertyChanging();
			entity.Car = null;
		}
		
		private void attach_PaymentsCarsMaintenances(PaymentsCarsMaintenance entity)
		{
			this.SendPropertyChanging();
			entity.Car = this;
		}
		
		private void detach_PaymentsCarsMaintenances(PaymentsCarsMaintenance entity)
		{
			this.SendPropertyChanging();
			entity.Car = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonID;
		
		private string _Username;
		
		private string _Email;
		
		private EntitySet<Car> _Cars;
		
		private EntitySet<InsurancePolicy> _InsurancePolicies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIDChanging(int value);
    partial void OnPersonIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public User()
		{
			this._Cars = new EntitySet<Car>(new Action<Car>(this.attach_Cars), new Action<Car>(this.detach_Cars));
			this._InsurancePolicies = new EntitySet<InsurancePolicy>(new Action<InsurancePolicy>(this.attach_InsurancePolicies), new Action<InsurancePolicy>(this.detach_InsurancePolicies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this.OnPersonIDChanging(value);
					this.SendPropertyChanging();
					this._PersonID = value;
					this.SendPropertyChanged("PersonID");
					this.OnPersonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Car", Storage="_Cars", ThisKey="PersonID", OtherKey="OwnerID")]
		public EntitySet<Car> Cars
		{
			get
			{
				return this._Cars;
			}
			set
			{
				this._Cars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_InsurancePolicy", Storage="_InsurancePolicies", ThisKey="PersonID", OtherKey="HolderID")]
		public EntitySet<InsurancePolicy> InsurancePolicies
		{
			get
			{
				return this._InsurancePolicies;
			}
			set
			{
				this._InsurancePolicies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cars(Car entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Cars(Car entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_InsurancePolicies(InsurancePolicy entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_InsurancePolicies(InsurancePolicy entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InsurancePolicies")]
	public partial class InsurancePolicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InsurancePolicyID;
		
		private string _Carrier;
		
		private string _PolicyNumber;
		
		private int _HolderID;
		
		private EntitySet<InsurancePoliciesForCar> _InsurancePoliciesForCars;
		
		private EntitySet<PaymentsInsurancePolicy> _PaymentsInsurancePolicies;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInsurancePolicyIDChanging(int value);
    partial void OnInsurancePolicyIDChanged();
    partial void OnCarrierChanging(string value);
    partial void OnCarrierChanged();
    partial void OnPolicyNumberChanging(string value);
    partial void OnPolicyNumberChanged();
    partial void OnHolderIDChanging(int value);
    partial void OnHolderIDChanged();
    #endregion
		
		public InsurancePolicy()
		{
			this._InsurancePoliciesForCars = new EntitySet<InsurancePoliciesForCar>(new Action<InsurancePoliciesForCar>(this.attach_InsurancePoliciesForCars), new Action<InsurancePoliciesForCar>(this.detach_InsurancePoliciesForCars));
			this._PaymentsInsurancePolicies = new EntitySet<PaymentsInsurancePolicy>(new Action<PaymentsInsurancePolicy>(this.attach_PaymentsInsurancePolicies), new Action<PaymentsInsurancePolicy>(this.detach_PaymentsInsurancePolicies));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePolicyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InsurancePolicyID
		{
			get
			{
				return this._InsurancePolicyID;
			}
			set
			{
				if ((this._InsurancePolicyID != value))
				{
					this.OnInsurancePolicyIDChanging(value);
					this.SendPropertyChanging();
					this._InsurancePolicyID = value;
					this.SendPropertyChanged("InsurancePolicyID");
					this.OnInsurancePolicyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrier", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Carrier
		{
			get
			{
				return this._Carrier;
			}
			set
			{
				if ((this._Carrier != value))
				{
					this.OnCarrierChanging(value);
					this.SendPropertyChanging();
					this._Carrier = value;
					this.SendPropertyChanged("Carrier");
					this.OnCarrierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyNumber", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PolicyNumber
		{
			get
			{
				return this._PolicyNumber;
			}
			set
			{
				if ((this._PolicyNumber != value))
				{
					this.OnPolicyNumberChanging(value);
					this.SendPropertyChanging();
					this._PolicyNumber = value;
					this.SendPropertyChanged("PolicyNumber");
					this.OnPolicyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HolderID", DbType="Int NOT NULL")]
		public int HolderID
		{
			get
			{
				return this._HolderID;
			}
			set
			{
				if ((this._HolderID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHolderIDChanging(value);
					this.SendPropertyChanging();
					this._HolderID = value;
					this.SendPropertyChanged("HolderID");
					this.OnHolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InsurancePolicy_InsurancePoliciesForCar", Storage="_InsurancePoliciesForCars", ThisKey="InsurancePolicyID", OtherKey="InsurancePolicyID")]
		public EntitySet<InsurancePoliciesForCar> InsurancePoliciesForCars
		{
			get
			{
				return this._InsurancePoliciesForCars;
			}
			set
			{
				this._InsurancePoliciesForCars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InsurancePolicy_PaymentsInsurancePolicy", Storage="_PaymentsInsurancePolicies", ThisKey="InsurancePolicyID", OtherKey="InsurancePolicyID")]
		public EntitySet<PaymentsInsurancePolicy> PaymentsInsurancePolicies
		{
			get
			{
				return this._PaymentsInsurancePolicies;
			}
			set
			{
				this._PaymentsInsurancePolicies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_InsurancePolicy", Storage="_User", ThisKey="HolderID", OtherKey="PersonID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.InsurancePolicies.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.InsurancePolicies.Add(this);
						this._HolderID = value.PersonID;
					}
					else
					{
						this._HolderID = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_InsurancePoliciesForCars(InsurancePoliciesForCar entity)
		{
			this.SendPropertyChanging();
			entity.InsurancePolicy = this;
		}
		
		private void detach_InsurancePoliciesForCars(InsurancePoliciesForCar entity)
		{
			this.SendPropertyChanging();
			entity.InsurancePolicy = null;
		}
		
		private void attach_PaymentsInsurancePolicies(PaymentsInsurancePolicy entity)
		{
			this.SendPropertyChanging();
			entity.InsurancePolicy = this;
		}
		
		private void detach_PaymentsInsurancePolicies(PaymentsInsurancePolicy entity)
		{
			this.SendPropertyChanging();
			entity.InsurancePolicy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InsurancePoliciesForCars")]
	public partial class InsurancePoliciesForCar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InsurancePolicyPerCarID;
		
		private int _InsurancePolicyID;
		
		private int _CarID;
		
		private System.DateTime _CoverageStart;
		
		private System.Nullable<System.DateTime> _CoverageEnd;
		
		private EntityRef<Car> _Car;
		
		private EntityRef<InsurancePolicy> _InsurancePolicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInsurancePolicyPerCarIDChanging(int value);
    partial void OnInsurancePolicyPerCarIDChanged();
    partial void OnInsurancePolicyIDChanging(int value);
    partial void OnInsurancePolicyIDChanged();
    partial void OnCarIDChanging(int value);
    partial void OnCarIDChanged();
    partial void OnCoverageStartChanging(System.DateTime value);
    partial void OnCoverageStartChanged();
    partial void OnCoverageEndChanging(System.Nullable<System.DateTime> value);
    partial void OnCoverageEndChanged();
    #endregion
		
		public InsurancePoliciesForCar()
		{
			this._Car = default(EntityRef<Car>);
			this._InsurancePolicy = default(EntityRef<InsurancePolicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePolicyPerCarID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InsurancePolicyPerCarID
		{
			get
			{
				return this._InsurancePolicyPerCarID;
			}
			set
			{
				if ((this._InsurancePolicyPerCarID != value))
				{
					this.OnInsurancePolicyPerCarIDChanging(value);
					this.SendPropertyChanging();
					this._InsurancePolicyPerCarID = value;
					this.SendPropertyChanged("InsurancePolicyPerCarID");
					this.OnInsurancePolicyPerCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePolicyID", DbType="Int NOT NULL")]
		public int InsurancePolicyID
		{
			get
			{
				return this._InsurancePolicyID;
			}
			set
			{
				if ((this._InsurancePolicyID != value))
				{
					if (this._InsurancePolicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInsurancePolicyIDChanging(value);
					this.SendPropertyChanging();
					this._InsurancePolicyID = value;
					this.SendPropertyChanged("InsurancePolicyID");
					this.OnInsurancePolicyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", DbType="Int NOT NULL")]
		public int CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					if (this._Car.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarIDChanging(value);
					this.SendPropertyChanging();
					this._CarID = value;
					this.SendPropertyChanged("CarID");
					this.OnCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoverageStart", DbType="DateTime NOT NULL")]
		public System.DateTime CoverageStart
		{
			get
			{
				return this._CoverageStart;
			}
			set
			{
				if ((this._CoverageStart != value))
				{
					this.OnCoverageStartChanging(value);
					this.SendPropertyChanging();
					this._CoverageStart = value;
					this.SendPropertyChanged("CoverageStart");
					this.OnCoverageStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoverageEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> CoverageEnd
		{
			get
			{
				return this._CoverageEnd;
			}
			set
			{
				if ((this._CoverageEnd != value))
				{
					this.OnCoverageEndChanging(value);
					this.SendPropertyChanging();
					this._CoverageEnd = value;
					this.SendPropertyChanged("CoverageEnd");
					this.OnCoverageEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_InsurancePoliciesForCar", Storage="_Car", ThisKey="CarID", OtherKey="CarID", IsForeignKey=true)]
		public Car Car
		{
			get
			{
				return this._Car.Entity;
			}
			set
			{
				Car previousValue = this._Car.Entity;
				if (((previousValue != value) 
							|| (this._Car.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car.Entity = null;
						previousValue.InsurancePoliciesForCars.Remove(this);
					}
					this._Car.Entity = value;
					if ((value != null))
					{
						value.InsurancePoliciesForCars.Add(this);
						this._CarID = value.CarID;
					}
					else
					{
						this._CarID = default(int);
					}
					this.SendPropertyChanged("Car");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InsurancePolicy_InsurancePoliciesForCar", Storage="_InsurancePolicy", ThisKey="InsurancePolicyID", OtherKey="InsurancePolicyID", IsForeignKey=true)]
		public InsurancePolicy InsurancePolicy
		{
			get
			{
				return this._InsurancePolicy.Entity;
			}
			set
			{
				InsurancePolicy previousValue = this._InsurancePolicy.Entity;
				if (((previousValue != value) 
							|| (this._InsurancePolicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._InsurancePolicy.Entity = null;
						previousValue.InsurancePoliciesForCars.Remove(this);
					}
					this._InsurancePolicy.Entity = value;
					if ((value != null))
					{
						value.InsurancePoliciesForCars.Add(this);
						this._InsurancePolicyID = value.InsurancePolicyID;
					}
					else
					{
						this._InsurancePolicyID = default(int);
					}
					this.SendPropertyChanged("InsurancePolicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MaintenanceTypes")]
	public partial class MaintenanceType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaintenanceTypeID;
		
		private string _Type;
		
		private EntitySet<PaymentsCarsMaintenance> _PaymentsCarsMaintenances;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaintenanceTypeIDChanging(int value);
    partial void OnMaintenanceTypeIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public MaintenanceType()
		{
			this._PaymentsCarsMaintenances = new EntitySet<PaymentsCarsMaintenance>(new Action<PaymentsCarsMaintenance>(this.attach_PaymentsCarsMaintenances), new Action<PaymentsCarsMaintenance>(this.detach_PaymentsCarsMaintenances));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaintenanceTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaintenanceTypeID
		{
			get
			{
				return this._MaintenanceTypeID;
			}
			set
			{
				if ((this._MaintenanceTypeID != value))
				{
					this.OnMaintenanceTypeIDChanging(value);
					this.SendPropertyChanging();
					this._MaintenanceTypeID = value;
					this.SendPropertyChanged("MaintenanceTypeID");
					this.OnMaintenanceTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MaintenanceType_PaymentsCarsMaintenance", Storage="_PaymentsCarsMaintenances", ThisKey="MaintenanceTypeID", OtherKey="MaintenanceTypeID")]
		public EntitySet<PaymentsCarsMaintenance> PaymentsCarsMaintenances
		{
			get
			{
				return this._PaymentsCarsMaintenances;
			}
			set
			{
				this._PaymentsCarsMaintenances.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PaymentsCarsMaintenances(PaymentsCarsMaintenance entity)
		{
			this.SendPropertyChanging();
			entity.MaintenanceType = this;
		}
		
		private void detach_PaymentsCarsMaintenances(PaymentsCarsMaintenance entity)
		{
			this.SendPropertyChanging();
			entity.MaintenanceType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentsCars")]
	public partial class PaymentsCar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaymentID;
		
		private int _CarID;
		
		private System.DateTime _Date;
		
		private decimal _Amount;
		
		private string _Payee;
		
		private EntityRef<Car> _Car;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentIDChanging(int value);
    partial void OnPaymentIDChanged();
    partial void OnCarIDChanging(int value);
    partial void OnCarIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnPayeeChanging(string value);
    partial void OnPayeeChanged();
    #endregion
		
		public PaymentsCar()
		{
			this._Car = default(EntityRef<Car>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaymentID
		{
			get
			{
				return this._PaymentID;
			}
			set
			{
				if ((this._PaymentID != value))
				{
					this.OnPaymentIDChanging(value);
					this.SendPropertyChanging();
					this._PaymentID = value;
					this.SendPropertyChanged("PaymentID");
					this.OnPaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", DbType="Int NOT NULL")]
		public int CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					if (this._Car.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarIDChanging(value);
					this.SendPropertyChanging();
					this._CarID = value;
					this.SendPropertyChanged("CarID");
					this.OnCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payee", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Payee
		{
			get
			{
				return this._Payee;
			}
			set
			{
				if ((this._Payee != value))
				{
					this.OnPayeeChanging(value);
					this.SendPropertyChanging();
					this._Payee = value;
					this.SendPropertyChanged("Payee");
					this.OnPayeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_PaymentsCar", Storage="_Car", ThisKey="CarID", OtherKey="CarID", IsForeignKey=true)]
		public Car Car
		{
			get
			{
				return this._Car.Entity;
			}
			set
			{
				Car previousValue = this._Car.Entity;
				if (((previousValue != value) 
							|| (this._Car.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car.Entity = null;
						previousValue.PaymentsCars.Remove(this);
					}
					this._Car.Entity = value;
					if ((value != null))
					{
						value.PaymentsCars.Add(this);
						this._CarID = value.CarID;
					}
					else
					{
						this._CarID = default(int);
					}
					this.SendPropertyChanged("Car");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentsCarsFuel")]
	public partial class PaymentsCarsFuel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FuelPaymentID;
		
		private int _CarID;
		
		private System.DateTime _Date;
		
		private decimal _CostPerGallon;
		
		private double _Gallons;
		
		private int _Octane;
		
		private double _MilesTank;
		
		private double _MilesTotal;
		
		private string _Station;
		
		private EntityRef<Car> _Car;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFuelPaymentIDChanging(int value);
    partial void OnFuelPaymentIDChanged();
    partial void OnCarIDChanging(int value);
    partial void OnCarIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnCostPerGallonChanging(decimal value);
    partial void OnCostPerGallonChanged();
    partial void OnGallonsChanging(double value);
    partial void OnGallonsChanged();
    partial void OnOctaneChanging(int value);
    partial void OnOctaneChanged();
    partial void OnMilesTankChanging(double value);
    partial void OnMilesTankChanged();
    partial void OnMilesTotalChanging(double value);
    partial void OnMilesTotalChanged();
    partial void OnStationChanging(string value);
    partial void OnStationChanged();
    #endregion
		
		public PaymentsCarsFuel()
		{
			this._Car = default(EntityRef<Car>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuelPaymentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FuelPaymentID
		{
			get
			{
				return this._FuelPaymentID;
			}
			set
			{
				if ((this._FuelPaymentID != value))
				{
					this.OnFuelPaymentIDChanging(value);
					this.SendPropertyChanging();
					this._FuelPaymentID = value;
					this.SendPropertyChanged("FuelPaymentID");
					this.OnFuelPaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", DbType="Int NOT NULL")]
		public int CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					if (this._Car.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarIDChanging(value);
					this.SendPropertyChanging();
					this._CarID = value;
					this.SendPropertyChanged("CarID");
					this.OnCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostPerGallon", DbType="Money NOT NULL")]
		public decimal CostPerGallon
		{
			get
			{
				return this._CostPerGallon;
			}
			set
			{
				if ((this._CostPerGallon != value))
				{
					this.OnCostPerGallonChanging(value);
					this.SendPropertyChanging();
					this._CostPerGallon = value;
					this.SendPropertyChanged("CostPerGallon");
					this.OnCostPerGallonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gallons", DbType="Float NOT NULL")]
		public double Gallons
		{
			get
			{
				return this._Gallons;
			}
			set
			{
				if ((this._Gallons != value))
				{
					this.OnGallonsChanging(value);
					this.SendPropertyChanging();
					this._Gallons = value;
					this.SendPropertyChanged("Gallons");
					this.OnGallonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Octane", DbType="Int NOT NULL")]
		public int Octane
		{
			get
			{
				return this._Octane;
			}
			set
			{
				if ((this._Octane != value))
				{
					this.OnOctaneChanging(value);
					this.SendPropertyChanging();
					this._Octane = value;
					this.SendPropertyChanged("Octane");
					this.OnOctaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilesTank", DbType="Float NOT NULL")]
		public double MilesTank
		{
			get
			{
				return this._MilesTank;
			}
			set
			{
				if ((this._MilesTank != value))
				{
					this.OnMilesTankChanging(value);
					this.SendPropertyChanging();
					this._MilesTank = value;
					this.SendPropertyChanged("MilesTank");
					this.OnMilesTankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilesTotal", DbType="Float NOT NULL")]
		public double MilesTotal
		{
			get
			{
				return this._MilesTotal;
			}
			set
			{
				if ((this._MilesTotal != value))
				{
					this.OnMilesTotalChanging(value);
					this.SendPropertyChanging();
					this._MilesTotal = value;
					this.SendPropertyChanged("MilesTotal");
					this.OnMilesTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Station", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Station
		{
			get
			{
				return this._Station;
			}
			set
			{
				if ((this._Station != value))
				{
					this.OnStationChanging(value);
					this.SendPropertyChanging();
					this._Station = value;
					this.SendPropertyChanged("Station");
					this.OnStationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_PaymentsCarsFuel", Storage="_Car", ThisKey="CarID", OtherKey="CarID", IsForeignKey=true)]
		public Car Car
		{
			get
			{
				return this._Car.Entity;
			}
			set
			{
				Car previousValue = this._Car.Entity;
				if (((previousValue != value) 
							|| (this._Car.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car.Entity = null;
						previousValue.PaymentsCarsFuels.Remove(this);
					}
					this._Car.Entity = value;
					if ((value != null))
					{
						value.PaymentsCarsFuels.Add(this);
						this._CarID = value.CarID;
					}
					else
					{
						this._CarID = default(int);
					}
					this.SendPropertyChanged("Car");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentsCarsMaintenance")]
	public partial class PaymentsCarsMaintenance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaintenancePaymentID;
		
		private int _CarID;
		
		private int _MaintenanceTypeID;
		
		private decimal _Amount;
		
		private System.DateTime _Date;
		
		private int _Miles;
		
		private string _Payee;
		
		private string _Note;
		
		private EntityRef<Car> _Car;
		
		private EntityRef<MaintenanceType> _MaintenanceType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaintenancePaymentIDChanging(int value);
    partial void OnMaintenancePaymentIDChanged();
    partial void OnCarIDChanging(int value);
    partial void OnCarIDChanged();
    partial void OnMaintenanceTypeIDChanging(int value);
    partial void OnMaintenanceTypeIDChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnMilesChanging(int value);
    partial void OnMilesChanged();
    partial void OnPayeeChanging(string value);
    partial void OnPayeeChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public PaymentsCarsMaintenance()
		{
			this._Car = default(EntityRef<Car>);
			this._MaintenanceType = default(EntityRef<MaintenanceType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaintenancePaymentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaintenancePaymentID
		{
			get
			{
				return this._MaintenancePaymentID;
			}
			set
			{
				if ((this._MaintenancePaymentID != value))
				{
					this.OnMaintenancePaymentIDChanging(value);
					this.SendPropertyChanging();
					this._MaintenancePaymentID = value;
					this.SendPropertyChanged("MaintenancePaymentID");
					this.OnMaintenancePaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarID", DbType="Int NOT NULL")]
		public int CarID
		{
			get
			{
				return this._CarID;
			}
			set
			{
				if ((this._CarID != value))
				{
					if (this._Car.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarIDChanging(value);
					this.SendPropertyChanging();
					this._CarID = value;
					this.SendPropertyChanged("CarID");
					this.OnCarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaintenanceTypeID", DbType="Int NOT NULL")]
		public int MaintenanceTypeID
		{
			get
			{
				return this._MaintenanceTypeID;
			}
			set
			{
				if ((this._MaintenanceTypeID != value))
				{
					if (this._MaintenanceType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaintenanceTypeIDChanging(value);
					this.SendPropertyChanging();
					this._MaintenanceTypeID = value;
					this.SendPropertyChanged("MaintenanceTypeID");
					this.OnMaintenanceTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miles", DbType="Int NOT NULL")]
		public int Miles
		{
			get
			{
				return this._Miles;
			}
			set
			{
				if ((this._Miles != value))
				{
					this.OnMilesChanging(value);
					this.SendPropertyChanging();
					this._Miles = value;
					this.SendPropertyChanged("Miles");
					this.OnMilesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payee", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Payee
		{
			get
			{
				return this._Payee;
			}
			set
			{
				if ((this._Payee != value))
				{
					this.OnPayeeChanging(value);
					this.SendPropertyChanging();
					this._Payee = value;
					this.SendPropertyChanged("Payee");
					this.OnPayeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Car_PaymentsCarsMaintenance", Storage="_Car", ThisKey="CarID", OtherKey="CarID", IsForeignKey=true)]
		public Car Car
		{
			get
			{
				return this._Car.Entity;
			}
			set
			{
				Car previousValue = this._Car.Entity;
				if (((previousValue != value) 
							|| (this._Car.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Car.Entity = null;
						previousValue.PaymentsCarsMaintenances.Remove(this);
					}
					this._Car.Entity = value;
					if ((value != null))
					{
						value.PaymentsCarsMaintenances.Add(this);
						this._CarID = value.CarID;
					}
					else
					{
						this._CarID = default(int);
					}
					this.SendPropertyChanged("Car");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MaintenanceType_PaymentsCarsMaintenance", Storage="_MaintenanceType", ThisKey="MaintenanceTypeID", OtherKey="MaintenanceTypeID", IsForeignKey=true)]
		public MaintenanceType MaintenanceType
		{
			get
			{
				return this._MaintenanceType.Entity;
			}
			set
			{
				MaintenanceType previousValue = this._MaintenanceType.Entity;
				if (((previousValue != value) 
							|| (this._MaintenanceType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MaintenanceType.Entity = null;
						previousValue.PaymentsCarsMaintenances.Remove(this);
					}
					this._MaintenanceType.Entity = value;
					if ((value != null))
					{
						value.PaymentsCarsMaintenances.Add(this);
						this._MaintenanceTypeID = value.MaintenanceTypeID;
					}
					else
					{
						this._MaintenanceTypeID = default(int);
					}
					this.SendPropertyChanged("MaintenanceType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentsInsurancePolicies")]
	public partial class PaymentsInsurancePolicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InsurancePolicyPaymentID;
		
		private int _InsurancePolicyID;
		
		private System.DateTime _Date;
		
		private decimal _Amount;
		
		private EntityRef<InsurancePolicy> _InsurancePolicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInsurancePolicyPaymentIDChanging(int value);
    partial void OnInsurancePolicyPaymentIDChanged();
    partial void OnInsurancePolicyIDChanging(int value);
    partial void OnInsurancePolicyIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    #endregion
		
		public PaymentsInsurancePolicy()
		{
			this._InsurancePolicy = default(EntityRef<InsurancePolicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePolicyPaymentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InsurancePolicyPaymentID
		{
			get
			{
				return this._InsurancePolicyPaymentID;
			}
			set
			{
				if ((this._InsurancePolicyPaymentID != value))
				{
					this.OnInsurancePolicyPaymentIDChanging(value);
					this.SendPropertyChanging();
					this._InsurancePolicyPaymentID = value;
					this.SendPropertyChanged("InsurancePolicyPaymentID");
					this.OnInsurancePolicyPaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePolicyID", DbType="Int NOT NULL")]
		public int InsurancePolicyID
		{
			get
			{
				return this._InsurancePolicyID;
			}
			set
			{
				if ((this._InsurancePolicyID != value))
				{
					if (this._InsurancePolicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInsurancePolicyIDChanging(value);
					this.SendPropertyChanging();
					this._InsurancePolicyID = value;
					this.SendPropertyChanged("InsurancePolicyID");
					this.OnInsurancePolicyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="InsurancePolicy_PaymentsInsurancePolicy", Storage="_InsurancePolicy", ThisKey="InsurancePolicyID", OtherKey="InsurancePolicyID", IsForeignKey=true)]
		public InsurancePolicy InsurancePolicy
		{
			get
			{
				return this._InsurancePolicy.Entity;
			}
			set
			{
				InsurancePolicy previousValue = this._InsurancePolicy.Entity;
				if (((previousValue != value) 
							|| (this._InsurancePolicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._InsurancePolicy.Entity = null;
						previousValue.PaymentsInsurancePolicies.Remove(this);
					}
					this._InsurancePolicy.Entity = value;
					if ((value != null))
					{
						value.PaymentsInsurancePolicies.Add(this);
						this._InsurancePolicyID = value.InsurancePolicyID;
					}
					else
					{
						this._InsurancePolicyID = default(int);
					}
					this.SendPropertyChanged("InsurancePolicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
