@startuml

header "Communication Center"

control "Request Handler" as RH
entity "Channel Manager" as CM
entity "Enhancement Manager" as EM
collections  "Enhancement Provider" as EP
entity "Message Composer" AS MC
entity "Template Resolver" as TR
entity "Target Manager" as TM
entity "Generate Text" AS GT
entity "Channel Provider" as CP

 -\ RH : Send Communication Request
 activate RH
 note right : target: string, messageType: string, extendedData: JObject | target, class(messageType, extendedData)

 RH -> CM : Get Target Channels
 note right : target, messageType
 activate CM
 CM --> RH : Channels[]
 note right : In Application Alerts | Email | SMS
 deactivate CM

 alt Channels.Count() > 0

    RH -> EM : Enhance
 note right : target, messageType, data : JObject
    activate EM

    group Chain Providers    
        EM -> EP : Enhance
        note right : target, messageType, data
        activate EP
        EP --> EM : data+
        deactivate EP
    end 


    EM --> RH : data+
    deactivate EM

    loop per Channel

        RH -\ MC : Compose
        note right : messageType, channel, target, culture, data
        activate MC
        deactivate RH
        
            MC -> TM : Get Contact Details
            note right : target, channel
            activate TM
            TM --> MC : (contact, culture)
            deactivate TM

            MC -> TR : Get Template
            note right : messageType, channel, culture
            activate TR
            TR --> MC : template
            deactivate TR

            MC -> GT : Generate
            note right : template, data
            activate GT
            GT --> MC : text
            deactivate GT

            MC -\ CP : Send Message
            activate CP
            deactivate MC
    
    end
end

@enduml