ALTER TABLE [dbo].[BasePaths]
    ADD CONSTRAINT [PK_BasePaths] PRIMARY KEY CLUSTERED ([BasePathID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

