ALTER TABLE [dbo].[Resources]
    ADD CONSTRAINT [PK_Resources] PRIMARY KEY CLUSTERED ([ResourceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

