ALTER TABLE [dbo].[ResourceAttributeTypes]
    ADD CONSTRAINT [PK_ResourceAttributeTypes] PRIMARY KEY CLUSTERED ([ResourceAttributeTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

