ALTER TABLE [dbo].[ResourceTypes]
    ADD CONSTRAINT [PK_ResourceTypes] PRIMARY KEY CLUSTERED ([ResourceTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

