ALTER TABLE [dbo].[ResourceAttributes]
    ADD CONSTRAINT [PK_ResourceAttributes] PRIMARY KEY CLUSTERED ([ResourceAttributeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

