ALTER TABLE [dbo].[Scalings]
    ADD CONSTRAINT [PK_Scalings] PRIMARY KEY CLUSTERED ([ScallingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

