ALTER TABLE [dbo].[AuthClaims]
    ADD CONSTRAINT [PK_AuthClaims] PRIMARY KEY CLUSTERED ([AuthClaimID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

