CREATE NONCLUSTERED INDEX [_dta_index_ResourceAttributes_8_981578535__K2_K3_4]
    ON [dbo].[ResourceAttributes]([ResourceAttributeTypeID] ASC, [ResourceID] ASC)
    INCLUDE([Value]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

