//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDocument
    {
        public int BillingDocument1 { get; set; }
        public System.DateTime DownloadedDate { get; set; }
        public byte[] Data { get; set; }
        public string Comment { get; set; }
        public int VendorID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
