//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarMaintenanceLogEntities : DbContext
    {
        public CarMaintenanceLogEntities()
            : base("name=CarMaintenanceLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<FillUp> FillUps { get; set; }
        public virtual DbSet<InsurancePayment> InsurancePayments { get; set; }
        public virtual DbSet<MaintenanceSchedule> MaintenanceSchedules { get; set; }
        public virtual DbSet<OilChange> OilChanges1 { get; set; }
        public virtual DbSet<OtherService> OtherServices { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Tire> Tires { get; set; }
        public virtual DbSet<CombinedCost> CombinedCosts { get; set; }
        public virtual DbSet<CostsPerCar> CostsPerCars { get; set; }
        public virtual DbSet<DriverCarMaintenance> DriverCarMaintenances { get; set; }
        public virtual DbSet<SummaryCosts_Yearly> SummaryCosts_Yearly { get; set; }
        public virtual DbSet<TotalMile> TotalMiles { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LineItem> LineItems { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<TimeLog> TimeLogs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<DetailedTimeLog> DetailedTimeLogs { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<SlidingBalance> SlidingBalances { get; set; }
        public virtual DbSet<FillUps_Locations> FillUps_Locations { get; set; }
        public virtual DbSet<ReportedTimeLog> ReportedTimeLogs { get; set; }
        public virtual DbSet<BillingDocument> BillingDocuments { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<EmployeeProject> EmployeeProjects { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual ObjectResult<string> XmlSummary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("XmlSummary");
        }
    
        public virtual ObjectResult<CreateAndRegisterReportedTimeLogs_Result> CreateAndRegisterReportedTimeLogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateAndRegisterReportedTimeLogs_Result>("CreateAndRegisterReportedTimeLogs");
        }
    
        public virtual ObjectResult<string> GetInvoiceXML(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetInvoiceXML", invoiceIDParameter);
        }
    }
}
