//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostsPerCar
    {
        public int CarID { get; set; }
        public Nullable<decimal> FillUps { get; set; }
        public Nullable<decimal> InsurancePayments { get; set; }
        public Nullable<decimal> Payments { get; set; }
        public Nullable<decimal> OilChanges { get; set; }
        public Nullable<decimal> OtherServices { get; set; }
        public Nullable<decimal> Tires { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
