//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedTimeLog
    {
        public int TimeLogID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> DoW { get; set; }
        public string DayOfWeek { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<System.TimeSpan> StartBreak { get; set; }
        public Nullable<System.TimeSpan> EndBreak { get; set; }
        public Nullable<System.TimeSpan> EndTIme { get; set; }
        public string Note { get; set; }
        public Nullable<double> Miles { get; set; }
        public Nullable<double> Hours { get; set; }
    }
}
