//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverCarMaintenance
    {
        public int DriverID { get; set; }
        public int CarID { get; set; }
        public int MaintenanceScheduleID { get; set; }
        public string Driver { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SubModel { get; set; }
        public decimal TotalMiles { get; set; }
        public decimal ScheduledMiles { get; set; }
        public Nullable<decimal> DueIn { get; set; }
        public string WorkItems { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    }
}
