//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FillUp
    {
        public int FillUpID { get; set; }
        public int CarID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal CostPerGallon { get; set; }
        public decimal Gallons { get; set; }
        public int Octane { get; set; }
        public decimal TankMiles { get; set; }
        public decimal TotalMiles { get; set; }
        public string Station { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ExtendedCost { get; set; }
        public Nullable<decimal> MilesPerGallon { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
