//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FillUps_Locations
    {
        public Nullable<int> StationID { get; set; }
        public int FillUpID { get; set; }
        public int CarID { get; set; }
        public int DriverID { get; set; }
        public string Station { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public decimal TankMiles { get; set; }
        public System.DateTime Date { get; set; }
        public int Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<long> OrderNumber { get; set; }
    }
}
