//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.LineItems = new HashSet<LineItem>();
        }
    
        public int InvoiceID { get; set; }
        public int CustomerID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int TermsID { get; set; }
        public string TermsAndConditions { get; set; }
        public string InvoiceStatusCode { get; set; }
        public byte[] RenderedInvoice { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Comment { get; set; }
        public int HasRenderedInvoice { get; set; }
        public string RenderedInvoiceMime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineItem> LineItems { get; set; }
    }
}
