//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int LineItemID { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public double ExtendedAmount { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public double TotalAmount { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
