//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceSchedule
    {
        public int MaintenanceScheduleID { get; set; }
        public int CarID { get; set; }
        public decimal Miles { get; set; }
        public string WorkItems { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
