//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilChange
    {
        public int OilChangeID { get; set; }
        public int CarID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal ChangeMiles { get; set; }
        public string OilBrand { get; set; }
        public string FilterBrand { get; set; }
        public Nullable<decimal> Quarts { get; set; }
        public Nullable<decimal> OilCost { get; set; }
        public Nullable<decimal> FilterCost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ExtendedCost { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
