//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherService
    {
        public int OtherServiceID { get; set; }
        public int CarID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Miles { get; set; }
        public string Item { get; set; }
        public decimal Cost { get; set; }
        public decimal Rate { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ExtendedCost { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
