//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int CarID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string PaidTo { get; set; }
        public string Notes { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
