//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlidingBalance
    {
        public int TransactionID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public string Note { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
