//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryCosts_Yearly
    {
        public int CarID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> YearlyCost { get; set; }
        public Nullable<decimal> TotalMiles { get; set; }
        public Nullable<decimal> MilesThisYear { get; set; }
        public Nullable<decimal> CostDifferenceYear { get; set; }
        public Nullable<decimal> CostPerMile { get; set; }
    }
}
