//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public Nullable<int> InvoiceID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<System.DateTime> FirstOfWeek { get; set; }
        public Nullable<double> Miles { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public Nullable<double> Saturday { get; set; }
        public Nullable<double> Sunday { get; set; }
        public Nullable<double> Monday { get; set; }
        public Nullable<double> Tuesday { get; set; }
        public Nullable<double> Wednesday { get; set; }
        public Nullable<double> Thursday { get; set; }
        public Nullable<double> Friday { get; set; }
        public Nullable<long> Row_Order { get; set; }
    }
}
