//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tire
    {
        public int TireID { get; set; }
        public int CarID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Miles { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public decimal Cost { get; set; }
        public int Quantity { get; set; }
        public decimal TaxRate { get; set; }
        public int WarrantyMonths { get; set; }
        public decimal WarrantyMiles { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> ExpireMiles { get; set; }
        public Nullable<decimal> ExtendedCost { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
