//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMaintenanceLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int CarID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<double> LoggedMiles { get; set; }
        public Nullable<decimal> TotalMiles { get; set; }
        public string PercentBusiness { get; set; }
        public Nullable<double> Expense { get; set; }
    }
}
