ALTER TABLE [Core].[SessionContexts]
    ADD CONSTRAINT [PK_SessionContexts] PRIMARY KEY CLUSTERED ([SessionContextID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

