CREATE TABLE [Storage].[ContentData] (
    [ContentDataID] INT                        IDENTITY (1, 1) NOT NULL,
    [RowID]         UNIQUEIDENTIFIER           ROWGUIDCOL NOT NULL,
    [Data]          VARBINARY (MAX) FILESTREAM NOT NULL,
    [Length]        AS                         (len([Data])) PERSISTED,
    [ContentItemID] INT                        DEFAULT ((0)) NULL,
    UNIQUE NONCLUSTERED ([RowID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY],
    CONSTRAINT [UQ_ContentData_RowID] UNIQUE NONCLUSTERED ([RowID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
);

