ALTER TABLE [dbo].[Media]
    ADD CONSTRAINT [aaaaaMedia_PK] PRIMARY KEY NONCLUSTERED ([LocalID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];



