/*ALTER TABLE [dbo].[GenreMedia]
    ADD CONSTRAINT [aaaaaGenreMedia_PK] PRIMARY KEY NONCLUSTERED ([GenreMediaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];*/

