ALTER TABLE [dbo].[GenreMedia]
    ADD CONSTRAINT [PK_GenreMedia] PRIMARY KEY CLUSTERED ([GenreID] ASC, [MediaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

