<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<IsPackable>false</IsPackable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest.TestAdapter" />
		<PackageReference Include="MSTest.TestFramework" />
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OoBDev.Microsoft.Azure.EventHub\OoBDev.Microsoft.Azure.EventHub.csproj" />
		<ProjectReference Include="..\OoBDev.Microsoft.Azure.ServiceBus\OoBDev.Microsoft.Azure.ServiceBus.csproj" />
		<ProjectReference Include="..\OoBDev.Microsoft.Azure.Storage\OoBDev.Microsoft.Azure.Storage.csproj" />
		<ProjectReference Include="..\OoBDev.ComplexEvents.Common\OoBDev.ComplexEvents.Common.csproj" />
		<ProjectReference Include="..\OoBDev.ComplexEvents.EntityFrameworkCore\OoBDev.ComplexEvents.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\OoBDev.EntityFrameworkCore.EmbeddedResources\OoBDev.EntityFrameworkCore.EmbeddedResources.csproj" Condition=" '$(TargetFramework)' == 'netstandard2.1' Or  '$(TargetFramework)' == 'netcoreapp3.1'" />
		<ProjectReference Include="..\OoBDev.IdentityModel.Extensions\OoBDev.IdentityModel.Extensions.csproj" />
		<ProjectReference Include="..\OoBDev.MessageQueueing\OoBDev.MessageQueueing.csproj" />
		<ProjectReference Include="..\OoBDev.TestUtilities\OoBDev.TestUtilities.csproj" />
		<ProjectReference Include="..\OoBDev.Toolkit\OoBDev.Toolkit.csproj" />
	</ItemGroup>

</Project>
