ALTER TABLE [Storage].[ContentItems]
    ADD CONSTRAINT [PK_ContentItems] PRIMARY KEY CLUSTERED ([ContentItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

