ALTER TABLE [Storage].[ContentMetaTypes]
    ADD CONSTRAINT [PK_ContentMetaTypes] PRIMARY KEY CLUSTERED ([ContentMetaTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

