ALTER TABLE [Storage].[ContentItemsInRoles]
    ADD CONSTRAINT [PK_ContentItemsInRoles] PRIMARY KEY NONCLUSTERED ([AssignmentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

