ALTER TABLE [Storage].[ContentTypes]
    ADD CONSTRAINT [PK_ContentTypes] PRIMARY KEY CLUSTERED ([ContentTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

