ALTER TABLE [Storage].[ContentData]
    ADD CONSTRAINT [PK_ContentData] PRIMARY KEY CLUSTERED ([ContentDataID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

