#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.Security.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyAuthentication")]
	public partial class DataMyAuthenticationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMySession(MySession instance);
    partial void UpdateMySession(MySession instance);
    partial void DeleteMySession(MySession instance);
    partial void InsertMyUser(MyUser instance);
    partial void UpdateMyUser(MyUser instance);
    partial void DeleteMyUser(MyUser instance);
    partial void InsertMyRole(MyRole instance);
    partial void UpdateMyRole(MyRole instance);
    partial void DeleteMyRole(MyRole instance);
    partial void InsertMyApplication(MyApplication instance);
    partial void UpdateMyApplication(MyApplication instance);
    partial void DeleteMyApplication(MyApplication instance);
    partial void InsertMyApplicationRole(MyApplicationRole instance);
    partial void UpdateMyApplicationRole(MyApplicationRole instance);
    partial void DeleteMyApplicationRole(MyApplicationRole instance);
    partial void InsertMyUserApplicationRole(MyUserApplicationRole instance);
    partial void UpdateMyUserApplicationRole(MyUserApplicationRole instance);
    partial void DeleteMyUserApplicationRole(MyUserApplicationRole instance);
    #endregion
		
		public DataMyAuthenticationDataContext() : 
				base(global::WhitedUS.Security.Properties.Settings.Default.MyAuthenticationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataMyAuthenticationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMyAuthenticationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMyAuthenticationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMyAuthenticationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MySession> MySessions
		{
			get
			{
				return this.GetTable<MySession>();
			}
		}
		
		public System.Data.Linq.Table<MyUser> MyUsers
		{
			get
			{
				return this.GetTable<MyUser>();
			}
		}
		
		public System.Data.Linq.Table<MyRole> MyRoles
		{
			get
			{
				return this.GetTable<MyRole>();
			}
		}
		
		public System.Data.Linq.Table<MyApplication> MyApplications
		{
			get
			{
				return this.GetTable<MyApplication>();
			}
		}
		
		public System.Data.Linq.Table<MyApplicationRole> MyApplicationRoles
		{
			get
			{
				return this.GetTable<MyApplicationRole>();
			}
		}
		
		public System.Data.Linq.Table<MyUserApplicationRole> MyUserApplicationRoles
		{
			get
			{
				return this.GetTable<MyUserApplicationRole>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MySession")]
	public partial class MySession : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UniqueID;
		
		private System.Guid _ApplicationID;
		
		private System.DateTime _DateCreated;
		
		private System.DateTime _DateExpired;
		
		private System.DateTime _DateLocked;
		
		private int _LockedId;
		
		private bool _Locked;
		
		private string _SessionItems;
		
		private int _Flags;
		
		private System.Guid _UserID;
		
		private EntityRef<MyUser> _MyUser;
		
		private EntityRef<MyApplication> _MyApplication;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniqueIDChanging(System.Guid value);
    partial void OnUniqueIDChanged();
    partial void OnApplicationIDChanging(System.Guid value);
    partial void OnApplicationIDChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnDateExpiredChanging(System.DateTime value);
    partial void OnDateExpiredChanged();
    partial void OnDateLockedChanging(System.DateTime value);
    partial void OnDateLockedChanged();
    partial void OnLockedIdChanging(int value);
    partial void OnLockedIdChanged();
    partial void OnLockedChanging(bool value);
    partial void OnLockedChanged();
    partial void OnSessionItemsChanging(string value);
    partial void OnSessionItemsChanged();
    partial void OnFlagsChanging(int value);
    partial void OnFlagsChanged();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    #endregion
		
		public MySession()
		{
			this._MyUser = default(EntityRef<MyUser>);
			this._MyApplication = default(EntityRef<MyApplication>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					if (this._MyApplication.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnApplicationIDChanging(value);
					this.SendPropertyChanging();
					this._ApplicationID = value;
					this.SendPropertyChanged("ApplicationID");
					this.OnApplicationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpired", DbType="DateTime NOT NULL")]
		public System.DateTime DateExpired
		{
			get
			{
				return this._DateExpired;
			}
			set
			{
				if ((this._DateExpired != value))
				{
					this.OnDateExpiredChanging(value);
					this.SendPropertyChanging();
					this._DateExpired = value;
					this.SendPropertyChanged("DateExpired");
					this.OnDateExpiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLocked", DbType="DateTime NOT NULL")]
		public System.DateTime DateLocked
		{
			get
			{
				return this._DateLocked;
			}
			set
			{
				if ((this._DateLocked != value))
				{
					this.OnDateLockedChanging(value);
					this.SendPropertyChanging();
					this._DateLocked = value;
					this.SendPropertyChanged("DateLocked");
					this.OnDateLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockedId", DbType="Int NOT NULL")]
		public int LockedId
		{
			get
			{
				return this._LockedId;
			}
			set
			{
				if ((this._LockedId != value))
				{
					this.OnLockedIdChanging(value);
					this.SendPropertyChanging();
					this._LockedId = value;
					this.SendPropertyChanged("LockedId");
					this.OnLockedIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locked", DbType="Bit NOT NULL")]
		public bool Locked
		{
			get
			{
				return this._Locked;
			}
			set
			{
				if ((this._Locked != value))
				{
					this.OnLockedChanging(value);
					this.SendPropertyChanging();
					this._Locked = value;
					this.SendPropertyChanged("Locked");
					this.OnLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionItems", DbType="NVarChar(MAX)")]
		public string SessionItems
		{
			get
			{
				return this._SessionItems;
			}
			set
			{
				if ((this._SessionItems != value))
				{
					this.OnSessionItemsChanging(value);
					this.SendPropertyChanging();
					this._SessionItems = value;
					this.SendPropertyChanged("SessionItems");
					this.OnSessionItemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flags", DbType="Int NOT NULL")]
		public int Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this.OnFlagsChanging(value);
					this.SendPropertyChanging();
					this._Flags = value;
					this.SendPropertyChanged("Flags");
					this.OnFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._MyUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyUser_MySession", Storage="_MyUser", ThisKey="UserID", OtherKey="UniqueID", IsForeignKey=true)]
		public MyUser MyUser
		{
			get
			{
				return this._MyUser.Entity;
			}
			set
			{
				MyUser previousValue = this._MyUser.Entity;
				if (((previousValue != value) 
							|| (this._MyUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MyUser.Entity = null;
						previousValue.MySessions.Remove(this);
					}
					this._MyUser.Entity = value;
					if ((value != null))
					{
						value.MySessions.Add(this);
						this._UserID = value.UniqueID;
					}
					else
					{
						this._UserID = default(System.Guid);
					}
					this.SendPropertyChanged("MyUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyApplication_MySession", Storage="_MyApplication", ThisKey="ApplicationID", OtherKey="UniqueID", IsForeignKey=true)]
		public MyApplication MyApplication
		{
			get
			{
				return this._MyApplication.Entity;
			}
			set
			{
				MyApplication previousValue = this._MyApplication.Entity;
				if (((previousValue != value) 
							|| (this._MyApplication.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MyApplication.Entity = null;
						previousValue.MySessions.Remove(this);
					}
					this._MyApplication.Entity = value;
					if ((value != null))
					{
						value.MySessions.Add(this);
						this._ApplicationID = value.UniqueID;
					}
					else
					{
						this._ApplicationID = default(System.Guid);
					}
					this.SendPropertyChanged("MyApplication");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyUser")]
	public partial class MyUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UniqueID;
		
		private string _UserName;
		
		private string _EmailAddress;
		
		private bool _IsDisabled;
		
		private bool _IsLocked;
		
		private string _PasswordHash;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _DateLastLogin;
		
		private System.Nullable<System.DateTime> _DateLastActivity;
		
		private System.Nullable<System.DateTime> _DateLastPasswordChange;
		
		private System.Nullable<System.DateTime> _DateLastLocked;
		
		private string _Comment;
		
		private string _ChangePasswordQuestion;
		
		private string _ChangePasswordAnswerHash;
		
		private EntitySet<MySession> _MySessions;
		
		private EntitySet<MyUserApplicationRole> _MyUserApplicationRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniqueIDChanging(System.Guid value);
    partial void OnUniqueIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnIsDisabledChanging(bool value);
    partial void OnIsDisabledChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnDateLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLastLoginChanged();
    partial void OnDateLastActivityChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLastActivityChanged();
    partial void OnDateLastPasswordChangeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLastPasswordChangeChanged();
    partial void OnDateLastLockedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLastLockedChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnChangePasswordQuestionChanging(string value);
    partial void OnChangePasswordQuestionChanged();
    partial void OnChangePasswordAnswerHashChanging(string value);
    partial void OnChangePasswordAnswerHashChanged();
    #endregion
		
		public MyUser()
		{
			this._MySessions = new EntitySet<MySession>(new Action<MySession>(this.attach_MySessions), new Action<MySession>(this.detach_MySessions));
			this._MyUserApplicationRoles = new EntitySet<MyUserApplicationRole>(new Action<MyUserApplicationRole>(this.attach_MyUserApplicationRoles), new Action<MyUserApplicationRole>(this.detach_MyUserApplicationRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDisabled", DbType="Bit NOT NULL")]
		public bool IsDisabled
		{
			get
			{
				return this._IsDisabled;
			}
			set
			{
				if ((this._IsDisabled != value))
				{
					this.OnIsDisabledChanging(value);
					this.SendPropertyChanging();
					this._IsDisabled = value;
					this.SendPropertyChanged("IsDisabled");
					this.OnIsDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastLogin
		{
			get
			{
				return this._DateLastLogin;
			}
			set
			{
				if ((this._DateLastLogin != value))
				{
					this.OnDateLastLoginChanging(value);
					this.SendPropertyChanging();
					this._DateLastLogin = value;
					this.SendPropertyChanged("DateLastLogin");
					this.OnDateLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastActivity", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastActivity
		{
			get
			{
				return this._DateLastActivity;
			}
			set
			{
				if ((this._DateLastActivity != value))
				{
					this.OnDateLastActivityChanging(value);
					this.SendPropertyChanging();
					this._DateLastActivity = value;
					this.SendPropertyChanged("DateLastActivity");
					this.OnDateLastActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastPasswordChange", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastPasswordChange
		{
			get
			{
				return this._DateLastPasswordChange;
			}
			set
			{
				if ((this._DateLastPasswordChange != value))
				{
					this.OnDateLastPasswordChangeChanging(value);
					this.SendPropertyChanging();
					this._DateLastPasswordChange = value;
					this.SendPropertyChanged("DateLastPasswordChange");
					this.OnDateLastPasswordChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastLocked", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastLocked
		{
			get
			{
				return this._DateLastLocked;
			}
			set
			{
				if ((this._DateLastLocked != value))
				{
					this.OnDateLastLockedChanging(value);
					this.SendPropertyChanging();
					this._DateLastLocked = value;
					this.SendPropertyChanged("DateLastLocked");
					this.OnDateLastLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangePasswordQuestion", DbType="NVarChar(1024)")]
		public string ChangePasswordQuestion
		{
			get
			{
				return this._ChangePasswordQuestion;
			}
			set
			{
				if ((this._ChangePasswordQuestion != value))
				{
					this.OnChangePasswordQuestionChanging(value);
					this.SendPropertyChanging();
					this._ChangePasswordQuestion = value;
					this.SendPropertyChanged("ChangePasswordQuestion");
					this.OnChangePasswordQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangePasswordAnswerHash", DbType="VarChar(50)")]
		public string ChangePasswordAnswerHash
		{
			get
			{
				return this._ChangePasswordAnswerHash;
			}
			set
			{
				if ((this._ChangePasswordAnswerHash != value))
				{
					this.OnChangePasswordAnswerHashChanging(value);
					this.SendPropertyChanging();
					this._ChangePasswordAnswerHash = value;
					this.SendPropertyChanged("ChangePasswordAnswerHash");
					this.OnChangePasswordAnswerHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyUser_MySession", Storage="_MySessions", ThisKey="UniqueID", OtherKey="UserID")]
		public EntitySet<MySession> MySessions
		{
			get
			{
				return this._MySessions;
			}
			set
			{
				this._MySessions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyUser_MyUserApplicationRole", Storage="_MyUserApplicationRoles", ThisKey="UniqueID", OtherKey="UserID")]
		public EntitySet<MyUserApplicationRole> MyUserApplicationRoles
		{
			get
			{
				return this._MyUserApplicationRoles;
			}
			set
			{
				this._MyUserApplicationRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MySessions(MySession entity)
		{
			this.SendPropertyChanging();
			entity.MyUser = this;
		}
		
		private void detach_MySessions(MySession entity)
		{
			this.SendPropertyChanging();
			entity.MyUser = null;
		}
		
		private void attach_MyUserApplicationRoles(MyUserApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyUser = this;
		}
		
		private void detach_MyUserApplicationRoles(MyUserApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyRole")]
	public partial class MyRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UniqueID;
		
		private string _RoleName;
		
		private string _Notes;
		
		private System.DateTime _DateCreated;
		
		private System.DateTime _DateModified;
		
		private EntitySet<MyApplicationRole> _MyApplicationRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniqueIDChanging(System.Guid value);
    partial void OnUniqueIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.DateTime value);
    partial void OnDateModifiedChanged();
    #endregion
		
		public MyRole()
		{
			this._MyApplicationRoles = new EntitySet<MyApplicationRole>(new Action<MyApplicationRole>(this.attach_MyApplicationRoles), new Action<MyApplicationRole>(this.detach_MyApplicationRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime NOT NULL")]
		public System.DateTime DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyRole_MyApplicationRole", Storage="_MyApplicationRoles", ThisKey="UniqueID", OtherKey="RoleID")]
		public EntitySet<MyApplicationRole> MyApplicationRoles
		{
			get
			{
				return this._MyApplicationRoles;
			}
			set
			{
				this._MyApplicationRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MyApplicationRoles(MyApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyRole = this;
		}
		
		private void detach_MyApplicationRoles(MyApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyRole = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyApplication")]
	public partial class MyApplication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UniqueID;
		
		private string _ApplicationName;
		
		private string _Notes;
		
		private System.DateTime _DateCreated;
		
		private System.DateTime _DateModified;
		
		private bool _IsEnabled;
		
		private EntitySet<MySession> _MySessions;
		
		private EntitySet<MyApplicationRole> _MyApplicationRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniqueIDChanging(System.Guid value);
    partial void OnUniqueIDChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.DateTime value);
    partial void OnDateModifiedChanged();
    partial void OnIsEnabledChanging(bool value);
    partial void OnIsEnabledChanged();
    #endregion
		
		public MyApplication()
		{
			this._MySessions = new EntitySet<MySession>(new Action<MySession>(this.attach_MySessions), new Action<MySession>(this.detach_MySessions));
			this._MyApplicationRoles = new EntitySet<MyApplicationRole>(new Action<MyApplicationRole>(this.attach_MyApplicationRoles), new Action<MyApplicationRole>(this.detach_MyApplicationRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime NOT NULL")]
		public System.DateTime DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnabled", DbType="Bit NOT NULL")]
		public bool IsEnabled
		{
			get
			{
				return this._IsEnabled;
			}
			set
			{
				if ((this._IsEnabled != value))
				{
					this.OnIsEnabledChanging(value);
					this.SendPropertyChanging();
					this._IsEnabled = value;
					this.SendPropertyChanged("IsEnabled");
					this.OnIsEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyApplication_MySession", Storage="_MySessions", ThisKey="UniqueID", OtherKey="ApplicationID")]
		public EntitySet<MySession> MySessions
		{
			get
			{
				return this._MySessions;
			}
			set
			{
				this._MySessions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyApplication_MyApplicationRole", Storage="_MyApplicationRoles", ThisKey="UniqueID", OtherKey="ApplicationID")]
		public EntitySet<MyApplicationRole> MyApplicationRoles
		{
			get
			{
				return this._MyApplicationRoles;
			}
			set
			{
				this._MyApplicationRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MySessions(MySession entity)
		{
			this.SendPropertyChanging();
			entity.MyApplication = this;
		}
		
		private void detach_MySessions(MySession entity)
		{
			this.SendPropertyChanging();
			entity.MyApplication = null;
		}
		
		private void attach_MyApplicationRoles(MyApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyApplication = this;
		}
		
		private void detach_MyApplicationRoles(MyApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyApplication = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyApplicationRole")]
	public partial class MyApplicationRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationID;
		
		private System.Guid _RoleID;
		
		private System.Guid _UniqueID;
		
		private System.DateTime _DateCreated;
		
		private EntitySet<MyUserApplicationRole> _MyUserApplicationRoles;
		
		private EntityRef<MyApplication> _MyApplication;
		
		private EntityRef<MyRole> _MyRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIDChanging(System.Guid value);
    partial void OnApplicationIDChanged();
    partial void OnRoleIDChanging(System.Guid value);
    partial void OnRoleIDChanged();
    partial void OnUniqueIDChanging(System.Guid value);
    partial void OnUniqueIDChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public MyApplicationRole()
		{
			this._MyUserApplicationRoles = new EntitySet<MyUserApplicationRole>(new Action<MyUserApplicationRole>(this.attach_MyUserApplicationRoles), new Action<MyUserApplicationRole>(this.detach_MyUserApplicationRoles));
			this._MyApplication = default(EntityRef<MyApplication>);
			this._MyRole = default(EntityRef<MyRole>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					if (this._MyApplication.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnApplicationIDChanging(value);
					this.SendPropertyChanging();
					this._ApplicationID = value;
					this.SendPropertyChanged("ApplicationID");
					this.OnApplicationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					if (this._MyRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UniqueID
		{
			get
			{
				return this._UniqueID;
			}
			set
			{
				if ((this._UniqueID != value))
				{
					this.OnUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._UniqueID = value;
					this.SendPropertyChanged("UniqueID");
					this.OnUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyApplicationRole_MyUserApplicationRole", Storage="_MyUserApplicationRoles", ThisKey="UniqueID", OtherKey="ApplicationRoleID")]
		public EntitySet<MyUserApplicationRole> MyUserApplicationRoles
		{
			get
			{
				return this._MyUserApplicationRoles;
			}
			set
			{
				this._MyUserApplicationRoles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyApplication_MyApplicationRole", Storage="_MyApplication", ThisKey="ApplicationID", OtherKey="UniqueID", IsForeignKey=true)]
		public MyApplication MyApplication
		{
			get
			{
				return this._MyApplication.Entity;
			}
			set
			{
				MyApplication previousValue = this._MyApplication.Entity;
				if (((previousValue != value) 
							|| (this._MyApplication.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MyApplication.Entity = null;
						previousValue.MyApplicationRoles.Remove(this);
					}
					this._MyApplication.Entity = value;
					if ((value != null))
					{
						value.MyApplicationRoles.Add(this);
						this._ApplicationID = value.UniqueID;
					}
					else
					{
						this._ApplicationID = default(System.Guid);
					}
					this.SendPropertyChanged("MyApplication");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyRole_MyApplicationRole", Storage="_MyRole", ThisKey="RoleID", OtherKey="UniqueID", IsForeignKey=true)]
		public MyRole MyRole
		{
			get
			{
				return this._MyRole.Entity;
			}
			set
			{
				MyRole previousValue = this._MyRole.Entity;
				if (((previousValue != value) 
							|| (this._MyRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MyRole.Entity = null;
						previousValue.MyApplicationRoles.Remove(this);
					}
					this._MyRole.Entity = value;
					if ((value != null))
					{
						value.MyApplicationRoles.Add(this);
						this._RoleID = value.UniqueID;
					}
					else
					{
						this._RoleID = default(System.Guid);
					}
					this.SendPropertyChanged("MyRole");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MyUserApplicationRoles(MyUserApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyApplicationRole = this;
		}
		
		private void detach_MyUserApplicationRoles(MyUserApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.MyApplicationRole = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyUserApplicationRole")]
	public partial class MyUserApplicationRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserID;
		
		private System.Guid _ApplicationRoleID;
		
		private EntityRef<MyApplicationRole> _MyApplicationRole;
		
		private EntityRef<MyUser> _MyUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    partial void OnApplicationRoleIDChanging(System.Guid value);
    partial void OnApplicationRoleIDChanged();
    #endregion
		
		public MyUserApplicationRole()
		{
			this._MyApplicationRole = default(EntityRef<MyApplicationRole>);
			this._MyUser = default(EntityRef<MyUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._MyUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationRoleID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ApplicationRoleID
		{
			get
			{
				return this._ApplicationRoleID;
			}
			set
			{
				if ((this._ApplicationRoleID != value))
				{
					if (this._MyApplicationRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnApplicationRoleIDChanging(value);
					this.SendPropertyChanging();
					this._ApplicationRoleID = value;
					this.SendPropertyChanged("ApplicationRoleID");
					this.OnApplicationRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyApplicationRole_MyUserApplicationRole", Storage="_MyApplicationRole", ThisKey="ApplicationRoleID", OtherKey="UniqueID", IsForeignKey=true)]
		public MyApplicationRole MyApplicationRole
		{
			get
			{
				return this._MyApplicationRole.Entity;
			}
			set
			{
				MyApplicationRole previousValue = this._MyApplicationRole.Entity;
				if (((previousValue != value) 
							|| (this._MyApplicationRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MyApplicationRole.Entity = null;
						previousValue.MyUserApplicationRoles.Remove(this);
					}
					this._MyApplicationRole.Entity = value;
					if ((value != null))
					{
						value.MyUserApplicationRoles.Add(this);
						this._ApplicationRoleID = value.UniqueID;
					}
					else
					{
						this._ApplicationRoleID = default(System.Guid);
					}
					this.SendPropertyChanged("MyApplicationRole");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MyUser_MyUserApplicationRole", Storage="_MyUser", ThisKey="UserID", OtherKey="UniqueID", IsForeignKey=true)]
		public MyUser MyUser
		{
			get
			{
				return this._MyUser.Entity;
			}
			set
			{
				MyUser previousValue = this._MyUser.Entity;
				if (((previousValue != value) 
							|| (this._MyUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MyUser.Entity = null;
						previousValue.MyUserApplicationRoles.Remove(this);
					}
					this._MyUser.Entity = value;
					if ((value != null))
					{
						value.MyUserApplicationRoles.Add(this);
						this._UserID = value.UniqueID;
					}
					else
					{
						this._UserID = default(System.Guid);
					}
					this.SendPropertyChanged("MyUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
