<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <UserSecretsId>aspnet-CarMaintenanceLog.Blazor-13092192-CB22-4AA4-9645-1996BE94A4B4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureADB2C.UI" Version="3.1.8" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarMaintenanceLog.Abstractions\CarMaintenanceLog.Abstractions.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Common\CarMaintenanceLog.Common.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Data.Core\CarMaintenanceLog.Data.Core.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Db\CarMaintenanceLog.Db.sqlproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Eventing\CarMaintenanceLog.Eventing.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Loader\CarMaintenanceLog.Loader.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Messaging\CarMaintenanceLog.Messaging.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.Models\CarMaintenanceLog.Models.csproj" />
    <ProjectReference Include="..\CarMaintenanceLog.SignalRClients\CarMaintenanceLog.SignalRClients.csproj" />
  </ItemGroup>

</Project>
