<?xml version="1.0" encoding="utf-8"?><Database Name="PhotoTags" Class="PhotoTagsDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=homeserver;Initial Catalog=PhotoTags;Integrated Security=True" SettingsObjectName="WhitedUS.Data.Properties.Settings" SettingsPropertyName="PhotoTagsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Image">
      <Column Name="ImageID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Folder" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="OldID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NewID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Image_Tag" Member="Tags" ThisKey="ImageID" OtherKey="ImageID" Type="Tag" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="ImageID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Image_Tag" Member="Image" ThisKey="ImageID" OtherKey="ImageID" Type="Image" IsForeignKey="true" />
    </Type>
  </Table>
</Database>