//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPhotoServicesTest.PhotoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.whited.us/2008/11/PhotoService", ConfigurationName="PhotoServiceReference.IPhotoServiceContract")]
    public interface IPhotoServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetDirectories", ReplyAction="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetDirectoriesRes" +
            "ponse")]
        string[] GetDirectories(string basePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetPhotoNames", ReplyAction="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetPhotoNamesResp" +
            "onse")]
        System.Collections.Generic.KeyValuePair<string, string>[] GetPhotoNames(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetImage", ReplyAction="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetImageResponse")]
        byte[] GetImage(string hashKey, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetImageResized", ReplyAction="http://www.whited.us/2008/11/PhotoService/IPhotoServiceContract/GetImageResizedRe" +
            "sponse")]
        byte[] GetImageResized(string hashKey, string path, int maxWidth, int maxHeight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhotoServiceContractChannel : WcfPhotoServicesTest.PhotoServiceReference.IPhotoServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhotoServiceContractClient : System.ServiceModel.ClientBase<WcfPhotoServicesTest.PhotoServiceReference.IPhotoServiceContract>, WcfPhotoServicesTest.PhotoServiceReference.IPhotoServiceContract {
        
        public PhotoServiceContractClient() {
        }
        
        public PhotoServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotoServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetDirectories(string basePath) {
            return base.Channel.GetDirectories(basePath);
        }
        
        public System.Collections.Generic.KeyValuePair<string, string>[] GetPhotoNames(string path) {
            return base.Channel.GetPhotoNames(path);
        }
        
        public byte[] GetImage(string hashKey, string path) {
            return base.Channel.GetImage(hashKey, path);
        }
        
        public byte[] GetImageResized(string hashKey, string path, int maxWidth, int maxHeight) {
            return base.Channel.GetImageResized(hashKey, path, maxWidth, maxHeight);
        }
    }
}
