using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WhitedUS.Drawing.Exif
{
    /// <remarks />
    public enum ExifIdType
    {
        /// <remarks />
        GpsVersionID = 0x0000,
        /// <remarks />
        GpsLatitudeRef = 0x0001,
        /// <remarks />
        GpsLatitude = 0x0002,
        /// <remarks />
        GpsLongitudeRef = 0x0003,
        /// <remarks />
        GpsLongitude = 0x0004,
        /// <remarks />
        GpsAltitudeRef = 0x0005,
        /// <remarks />
        GpsAltitude = 0x0006,
        /// <remarks />
        GpsTimeStamp = 0x0007,
        /// <remarks />
        GpsSatellites = 0x0008,
        /// <remarks />
        GpsStatus = 0x0009,
        /// <remarks />
        GpsMeasureMode = 0x00A,
        /// <remarks />
        GpsDOP = 0x000B,
        /// <remarks />
        GpsSpeedRef = 0x000C,
        /// <remarks />
        GpsSpeed = 0x000D,
        /// <remarks />
        GpsTrackRef = 0x000E,
        /// <remarks />
        GpsTrack = 0x000F,
        /// <remarks />
        GpsImgDirectionRef = 0x0010,
        /// <remarks />
        GpsImgDirection = 0x0011,
        /// <remarks />
        GpsMapDatum = 0x0012,
        /// <remarks />
        GpsDestLatitudeRef = 0x0013,
        /// <remarks />
        GpsDestLatitude = 0x0014,
        /// <remarks />
        GpsDestLongitudeRef = 0x0015,
        /// <remarks />
        GpsDestLongitude = 0x0016,
        /// <remarks />
        GpsDestBearingRef = 0x0017,
        /// <remarks />
        GpsDestBearing = 0x0018,
        /// <remarks />
        GpsDestDistanceRef = 0x0019,
        /// <remarks />
        GpsDestDistance = 0x001A,
        /// <remarks />
        GpsProcessingMethod = 0x001B,
        /// <remarks />
        GpsAreaInformation = 0x001C,
        /// <remarks />
        GpsDateStamp = 0x001D,
        /// <remarks />
        GpsDifferential = 0x001E,
        /// <remarks />
        NewSubfileType = 0x00FE,
        /// <remarks />
        SubfileType = 0x00FF,
        /// <remarks />
        ImageWidth = 0x0100,
        /// <remarks />
        ImageLength = 0x0101,
        /// <remarks />
        BitsPerSample = 0x0102,
        /// <remarks />
        Compression = 0x0103,
        /// <remarks />
        PhotoMetricInterpertation = 0x0106,
        /// <remarks />
        ThreshHolding = 0x0107,
        /// <remarks />
        CellWidth = 0x0108,
        /// <remarks />
        CellHeight = 0x0109,
        /// <remarks />
        FillOrder = 0x010A,
        /// <remarks />
        DocumentName = 0x010D,
        /// <remarks />
        ImageDescription = 0x010E,
        /// <remarks />
        Make = 0x010F,
        /// <remarks />
        Model = 0x0110,
        /// <remarks />
        StripOffset = 0x0111,
        /// <remarks />
        Orientation = 0x0112,
        /// <remarks />
        SamplesPerPixel = 0x0115,
        /// <remarks />
        RowsPerStrip = 0x0116,
        /// <remarks />
        StripBytesCount = 0x0117,
        /// <remarks />
        MinSampleValue = 0x0118,
        /// <remarks />
        MaxSampleValue = 0x0119,
        /// <remarks />
        XResolution = 0x011A,
        /// <remarks />
        YResolution = 0x011B,
        /// <remarks />
        PlanarConfiguration = 0x011C,
        /// <remarks />
        PageName = 0x011D,
        /// <remarks />
        XPosition = 0x011E,
        /// <remarks />
        YPosition = 0x011F,
        /// <remarks />
        FreeOffset = 0x0120,
        /// <remarks />
        FreeByteCounts = 0x0121,
        /// <remarks />
        GrayResponseUnit = 0x0122,
        /// <remarks />
        GrayResponseCurve = 0x0123,
        /// <remarks />
        T4Option = 0x0124,
        /// <remarks />
        T6Option = 0x0125,
        /// <remarks />
        ResolutionUnit = 0x0128,
        /// <remarks />
        PageNumber = 0x0129,
        /// <remarks />
        TransferFunction = 0x012D,
        /// <remarks />
        Software = 0x0131,
        /// <remarks />
        DateTime = 0x0132,
        /// <remarks />
        Artist = 0x013B,
        /// <remarks />
        HostComputer = 0x013C,
        /// <remarks />
        Predictor = 0x013D,
        /// <remarks />
        WhitePoint = 0x013E,
        /// <remarks />
        PrimaryChromaticities = 0x013F,
        /// <remarks />
        ColorMap = 0x0140,
        /// <remarks />
        HalftoneHints = 0x0141,
        /// <remarks />
        TileWidth = 0x0142,
        /// <remarks />
        TileLength = 0x0143,
        /// <remarks />
        TileOffset = 0x0144,
        /// <remarks />
        TileByteCounts = 0x0145,
        /// <remarks />
        InkSet = 0x014C,
        /// <remarks />
        InkNames = 0x014D,
        /// <remarks />
        NumberOfInks = 0x014E,
        /// <remarks />
        DotRange = 0x0150,
        /// <remarks />
        TargetPrinter = 0x0151,
        /// <remarks />
        ExtraSamples = 0x0152,
        /// <remarks />
        SampleFormat = 0x0153,
        /// <remarks />
        SMinSampleValue = 0x0154,
        /// <remarks />
        SMaxSampleValue = 0x0155,
        /// <remarks />
        TransferRange = 0x0156,
        /// <remarks />
        JPEGProc = 0x0200,
        /// <remarks />
        JPEGInterchangeFormat = 0x0201,
        /// <remarks />
        JPEGInterchangeFormatLength = 0x0202,
        /// <remarks />
        JPEGRestartInterval = 0x0203,
        /// <remarks />
        JPEGLosslessPredictors = 0x0205,
        /// <remarks />
        JPEGPointTransforms = 0x0206,
        /// <remarks />
        JPEGQTables = 0x0207,
        /// <remarks />
        JPEGDCTables = 0x0208,
        /// <remarks />
        JPEGACTables = 0x0209,
        /// <remarks />
        YCbCrCoefficients = 0x0211,
        /// <remarks />
        YCbCrSubsampling = 0x0212,
        /// <remarks />
        YCbCrPositioning = 0x0213,
        /// <remarks />
        ReferenceBlackWhite = 0x0214,
        /// <remarks />
        Gamma = 0x0301,
        /// <remarks />
        ICCProfileDescriptor = 0x0302,
        /// <remarks />
        SRGBRenderingIntent = 0x0303,
        /// <remarks />
        ImageTitle = 0x0320,
        /// <remarks />
        ResolutionXUnit = 0x5001,
        /// <remarks />
        ResolutionYUnit = 0x5002,
        /// <remarks />
        ResolutionXLengthUnit = 0x5003,
        /// <remarks />
        ResolutionYLengthUnit = 0x5004,
        /// <remarks />
        PrintFlags = 0x5005,
        /// <remarks />
        PrintFlagsVersion = 0x5006,
        /// <remarks />
        PrintFlagsCrop = 0x5007,
        /// <remarks />
        PrintFlagsBleedWidth = 0x5008,
        /// <remarks />
        PrintFlagsBleedWidthScale = 0x5009,
        /// <remarks />
        HalftoneLPI = 0x500A,
        /// <remarks />
        HalftoneLPIUnit = 0x500B,
        /// <remarks />
        HalftoneDegree = 0x500C,
        /// <remarks />
        HalftoneShape = 0x500D,
        /// <remarks />
        HalftoneMisc = 0x500E,
        /// <remarks />
        HalftoneScreen = 0x500F,
        /// <remarks />
        JPEGQuality = 0x5010,
        /// <remarks />
        GridSize = 0x5011,
        /// <remarks />
        ThumbnailFormat = 0x5012,
        /// <remarks />
        ThumbnailWidth = 0x5013,
        /// <remarks />
        ThumbnailHeight = 0x5014,
        /// <remarks />
        ThumbnailColorDepth = 0x5015,
        /// <remarks />
        ThumbnailPlanes = 0x5016,
        /// <remarks />
        ThumbnailRawBytes = 0x5017,
        /// <remarks />
        ThumbnailSize = 0x5018,
        /// <remarks />
        ThumbnailCompressedSize = 0x5019,
        /// <remarks />
        ColorTransferFunction = 0x501A,
        /// <remarks />
        ThumbnailData = 0x501B,
        /// <remarks />
        ThumbnailImageWidth = 0x5020,
        /// <remarks />
        ThumbnailImageHeight = 0x5021,
        /// <remarks />
        ThumbnailBitsPerSample = 0x5022,
        /// <remarks />
        ThumbnailCompression = 0x5023,
        /// <remarks />
        ThumbnailPhotometricInterp = 0x5024,
        /// <remarks />
        ThumbnailImageDescription = 0x5025,
        /// <remarks />
        ThumbnailEquipMake = 0x5026,
        /// <remarks />
        ThumbnailEquipModel = 0x5027,
        /// <remarks />
        ThumbnailStripOffsets = 0x5028,
        /// <remarks />
        ThumbnailOrientation = 0x5029,
        /// <remarks />
        ThumbnailSamplesPerPixel = 0x502A,
        /// <remarks />
        ThumbnailRowsPerStrip = 0x502B,
        /// <remarks />
        ThumbnailStripBytesCount = 0x502C,
        /// <remarks />
        ThumbnailResolutionX = 0x502D,
        /// <remarks />
        ThumbnailResolutionY = 0x502E,
        /// <remarks />
        ThumbnailPlanarConfig = 0x502F,
        /// <remarks />
        ThumbnailResolutionUnit = 0x5030,
        /// <remarks />
        ThumbnailTransferFunction = 0x5031,
        /// <remarks />
        ThumbnailSoftwareUsed = 0x5032,
        /// <remarks />
        ThumbnailDateTime = 0x5033,
        /// <remarks />
        ThumbnailArtist = 0x5034,
        /// <remarks />
        ThumbnailWhitePoint = 0x5035,
        /// <remarks />
        ThumbnailPrimaryChromaticities = 0x5036,
        /// <remarks />
        ThumbnailYCbCrCoefficients = 0x5037,
        /// <remarks />
        ThumbnailYCbCrSubsampling = 0x5038,
        /// <remarks />
        ThumbnailYCbCrPositioning = 0x5039,
        /// <remarks />
        ThumbnailRefBlackWhite = 0x503A,
        /// <remarks />
        ThumbnailCopyRight = 0x503B,
        /// <remarks />
        LuminanceTable = 0x5090,
        /// <remarks />
        ChrominanceTable = 0x5091,
        /// <remarks />
        FrameDelay = 0x5100,
        /// <remarks />
        LoopCount = 0x5101,
        /// <remarks />
        GlobalPalette = 0x5102,
        /// <remarks />
        IndexBackground = 0x5103,
        /// <remarks />
        IndexTransparent = 0x5104,
        /// <remarks />
        PixelUnit = 0x5110,
        /// <remarks />
        PixelPerUnitX = 0x5111,
        /// <remarks />
        PixelPerUnitY = 0x5112,
        /// <remarks />
        PaletteHistogram = 0x5113,
        /// <remarks />
        Copyright = 0x8298,
        /// <remarks />
        ExposureTime = 0x829A,
        /// <remarks />
        FNumber = 0x829D,
        /// <remarks />
        IFD = 0x8769,
        /// <remarks />
        ICCProfile = 0x8773,
        /// <remarks />
        ExposureProgram = 0x8822,
        /// <remarks />
        SpectralSensitivity = 0x8824,
        /// <remarks />
        GpsIFD = 0x8825,
        /// <remarks />
        ISOSpeedRatings = 0x8827,
        /// <remarks />
        OptoelectricConversionFactor = 0x8828,
        /// <remarks />
        ExifVersion = 0x9000,
        /// <remarks />
        DateTimeOriginal = 0x9003,
        /// <remarks />
        DateTimeDigitized = 0x9004,
        /// <remarks />
        ComponentsConfiguration = 0x9101,
        /// <remarks />
        CompressedBitsPerPixel = 0x9102,
        /// <remarks />
        ShutterSpeedValue = 0x9201,
        /// <remarks />
        ApertureValue = 0x9202,
        /// <remarks />
        BrightnessValue = 0x9203,
        /// <remarks />
        ExposureBiasValue = 0x9204,
        /// <remarks />
        MaxApertureValue = 0x9205,
        /// <remarks />
        SubjectDistance = 0x9206,
        /// <remarks />
        MeteringMode = 0x9207,
        /// <remarks />
        LightSource = 0x9208,
        /// <remarks />
        Flash = 0x9209,
        /// <remarks />
        FocalLength = 0x920A,
        /// <remarks />
        MakerNote = 0x927C,
        /// <remarks />
        UserComment = 0x9286,
        /// <remarks />
        SubSecTime = 0x9290,
        /// <remarks />
        SubSecTimeOriginal = 0x9291,
        /// <remarks />
        SubSecTimeDigitized = 0x9292,
        /// <remarks />
        FlashpixVersion = 0xA000,
        /// <remarks />
        ColorSpace = 0xA001,
        /// <remarks />
        PixelXDimension = 0xA002,
        /// <remarks />
        PixelYDimension = 0xA003,
        /// <remarks />
        RelatedSoundFile = 0xA004,
        /// <remarks />
        Interop = 0xA005,
        /// <remarks />
        FlashEnergy = 0xA20B,
        /// <remarks />
        SpatialFrequenceResponse = 0xA20C,
        /// <remarks />
        FocalPlaneXResolution = 0xA20E,
        /// <remarks />
        FocalPlaneYResolution = 0xA20F,
        /// <remarks />
        FocalPlaneResolutionUnit = 0xA210,
        /// <remarks />
        SubjectLocation = 0xA214,
        /// <remarks />
        ExposureIndex = 0xA215,
        /// <remarks />
        SensingMethod = 0xA217,
        /// <remarks />
        FileSource = 0xA300,
        /// <remarks />
        SceneType = 0xA301,
        /// <remarks />
        CfaPattern = 0xA302,
        /// <remarks />
        ImageUniqueId = 0xA420,
        /// <remarks />
        SubjectArea = 0x9214,
        /// <remarks />
        CustomRendered = 0xA401,
        /// <remarks />
        ExposureMode = 0xA402,
        /// <remarks />
        WhiteBalance = 0xA403,
        /// <remarks />
        DigitalZoomRatio = 0xA404,
        /// <remarks />
        FlocalLengthIn35mmFilm = 0xA405,
        /// <remarks />
        SceneCaptureType = 0xA406,
        /// <remarks />
        GainControl = 0xA407,
        /// <remarks />
        Contrast = 0xA408,
        /// <remarks />
        Saturation = 0xA409,
        /// <remarks />
        Sharpness = 0xA40A,
        /// <remarks />
        DeviceSettingDescription = 0xA40B,
        /// <remarks />
        SubjectDistanceRange = 0xA40C,
        /// <remarks />
        InterOperabilityIndex = 0x5041,
        /// <remarks />
        InterOperabilityVersion = 0x5042,
    }
}
