//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MediaCollectionModel", "FK_MediaTypes_CodeTypes", "CodeType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WhitedUS.MediaLibrary.Data.CodeType), "MediaType", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WhitedUS.MediaLibrary.Data.MediaType), true)]
[assembly: EdmRelationshipAttribute("MediaCollectionModel", "FK_Media_MediaTypes1", "MediaType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WhitedUS.MediaLibrary.Data.MediaType), "Medium", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WhitedUS.MediaLibrary.Data.Medium), true)]
[assembly: EdmRelationshipAttribute("MediaCollectionModel", "GenreMedia", "Genre", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WhitedUS.MediaLibrary.Data.Genre), "Medium", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WhitedUS.MediaLibrary.Data.Medium))]

#endregion

namespace WhitedUS.MediaLibrary.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MediaCollectionEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MediaCollectionEntities object using the connection string found in the 'MediaCollectionEntities' section of the application configuration file.
        /// </summary>
        public MediaCollectionEntities() : base("name=MediaCollectionEntities", "MediaCollectionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaCollectionEntities object.
        /// </summary>
        public MediaCollectionEntities(string connectionString) : base(connectionString, "MediaCollectionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaCollectionEntities object.
        /// </summary>
        public MediaCollectionEntities(EntityConnection connection) : base(connection, "MediaCollectionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CodeType> CodeTypes
        {
            get
            {
                if ((_CodeTypes == null))
                {
                    _CodeTypes = base.CreateObjectSet<CodeType>("CodeTypes");
                }
                return _CodeTypes;
            }
        }
        private ObjectSet<CodeType> _CodeTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Genre> Genres
        {
            get
            {
                if ((_Genres == null))
                {
                    _Genres = base.CreateObjectSet<Genre>("Genres");
                }
                return _Genres;
            }
        }
        private ObjectSet<Genre> _Genres;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Medium> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Medium>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Medium> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaType> MediaTypes
        {
            get
            {
                if ((_MediaTypes == null))
                {
                    _MediaTypes = base.CreateObjectSet<MediaType>("MediaTypes");
                }
                return _MediaTypes;
            }
        }
        private ObjectSet<MediaType> _MediaTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CodeTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodeTypes(CodeType codeType)
        {
            base.AddObject("CodeTypes", codeType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Genres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGenres(Genre genre)
        {
            base.AddObject("Genres", genre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Medium medium)
        {
            base.AddObject("Media", medium);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaTypes(MediaType mediaType)
        {
            base.AddObject("MediaTypes", mediaType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MediaCollectionModel", Name="CodeType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CodeType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CodeType object.
        /// </summary>
        /// <param name="localID">Initial value of the LocalID property.</param>
        public static CodeType CreateCodeType(global::System.Int32 localID)
        {
            CodeType codeType = new CodeType();
            codeType.LocalID = localID;
            return codeType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalID
        {
            get
            {
                return _LocalID;
            }
            set
            {
                if (_LocalID != value)
                {
                    OnLocalIDChanging(value);
                    ReportPropertyChanging("LocalID");
                    _LocalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocalID");
                    OnLocalIDChanged();
                }
            }
        }
        private global::System.Int32 _LocalID;
        partial void OnLocalIDChanging(global::System.Int32 value);
        partial void OnLocalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Long
        {
            get
            {
                return _Long;
            }
            set
            {
                OnLongChanging(value);
                ReportPropertyChanging("Long");
                _Long = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Long");
                OnLongChanged();
            }
        }
        private global::System.String _Long;
        partial void OnLongChanging(global::System.String value);
        partial void OnLongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MediaCollectionModel", "FK_MediaTypes_CodeTypes", "MediaType")]
        public EntityCollection<MediaType> MediaTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MediaType>("MediaCollectionModel.FK_MediaTypes_CodeTypes", "MediaType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MediaType>("MediaCollectionModel.FK_MediaTypes_CodeTypes", "MediaType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MediaCollectionModel", Name="Genre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Genre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Genre object.
        /// </summary>
        /// <param name="localID">Initial value of the LocalID property.</param>
        public static Genre CreateGenre(global::System.Int32 localID)
        {
            Genre genre = new Genre();
            genre.LocalID = localID;
            return genre;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalID
        {
            get
            {
                return _LocalID;
            }
            set
            {
                if (_LocalID != value)
                {
                    OnLocalIDChanging(value);
                    ReportPropertyChanging("LocalID");
                    _LocalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocalID");
                    OnLocalIDChanged();
                }
            }
        }
        private global::System.Int32 _LocalID;
        partial void OnLocalIDChanging(global::System.Int32 value);
        partial void OnLocalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MediaCollectionModel", "GenreMedia", "Medium")]
        public EntityCollection<Medium> Media
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Medium>("MediaCollectionModel.GenreMedia", "Medium");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Medium>("MediaCollectionModel.GenreMedia", "Medium", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MediaCollectionModel", Name="MediaType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaType object.
        /// </summary>
        /// <param name="localID">Initial value of the LocalID property.</param>
        /// <param name="codeTypeID">Initial value of the CodeTypeID property.</param>
        public static MediaType CreateMediaType(global::System.Int32 localID, global::System.Int32 codeTypeID)
        {
            MediaType mediaType = new MediaType();
            mediaType.LocalID = localID;
            mediaType.CodeTypeID = codeTypeID;
            return mediaType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalID
        {
            get
            {
                return _LocalID;
            }
            set
            {
                if (_LocalID != value)
                {
                    OnLocalIDChanging(value);
                    ReportPropertyChanging("LocalID");
                    _LocalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocalID");
                    OnLocalIDChanged();
                }
            }
        }
        private global::System.Int32 _LocalID;
        partial void OnLocalIDChanging(global::System.Int32 value);
        partial void OnLocalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeTypeID
        {
            get
            {
                return _CodeTypeID;
            }
            set
            {
                OnCodeTypeIDChanging(value);
                ReportPropertyChanging("CodeTypeID");
                _CodeTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodeTypeID");
                OnCodeTypeIDChanged();
            }
        }
        private global::System.Int32 _CodeTypeID;
        partial void OnCodeTypeIDChanging(global::System.Int32 value);
        partial void OnCodeTypeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MediaCollectionModel", "FK_MediaTypes_CodeTypes", "CodeType")]
        public CodeType CodeType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodeType>("MediaCollectionModel.FK_MediaTypes_CodeTypes", "CodeType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodeType>("MediaCollectionModel.FK_MediaTypes_CodeTypes", "CodeType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CodeType> CodeTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CodeType>("MediaCollectionModel.FK_MediaTypes_CodeTypes", "CodeType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CodeType>("MediaCollectionModel.FK_MediaTypes_CodeTypes", "CodeType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MediaCollectionModel", "FK_Media_MediaTypes1", "Medium")]
        public EntityCollection<Medium> Media
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Medium>("MediaCollectionModel.FK_Media_MediaTypes1", "Medium");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Medium>("MediaCollectionModel.FK_Media_MediaTypes1", "Medium", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MediaCollectionModel", Name="Medium")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medium : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Medium object.
        /// </summary>
        /// <param name="localID">Initial value of the LocalID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="mediaTypeID">Initial value of the MediaTypeID property.</param>
        /// <param name="have">Initial value of the Have property.</param>
        public static Medium CreateMedium(global::System.Int32 localID, global::System.String title, global::System.Int32 mediaTypeID, global::System.Boolean have)
        {
            Medium medium = new Medium();
            medium.LocalID = localID;
            medium.Title = title;
            medium.MediaTypeID = mediaTypeID;
            medium.Have = have;
            return medium;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalID
        {
            get
            {
                return _LocalID;
            }
            set
            {
                if (_LocalID != value)
                {
                    OnLocalIDChanging(value);
                    ReportPropertyChanging("LocalID");
                    _LocalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocalID");
                    OnLocalIDChanged();
                }
            }
        }
        private global::System.Int32 _LocalID;
        partial void OnLocalIDChanging(global::System.Int32 value);
        partial void OnLocalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private global::System.String _Rating;
        partial void OnRatingChanging(global::System.String value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.String _Year;
        partial void OnYearChanging(global::System.String value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Format
        {
            get
            {
                return _Format;
            }
            set
            {
                OnFormatChanging(value);
                ReportPropertyChanging("Format");
                _Format = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Format");
                OnFormatChanged();
            }
        }
        private global::System.String _Format;
        partial void OnFormatChanging(global::System.String value);
        partial void OnFormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private global::System.String _Length;
        partial void OnLengthChanging(global::System.String value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaTypeID
        {
            get
            {
                return _MediaTypeID;
            }
            set
            {
                OnMediaTypeIDChanging(value);
                ReportPropertyChanging("MediaTypeID");
                _MediaTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MediaTypeID");
                OnMediaTypeIDChanged();
            }
        }
        private global::System.Int32 _MediaTypeID;
        partial void OnMediaTypeIDChanging(global::System.Int32 value);
        partial void OnMediaTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Have
        {
            get
            {
                return _Have;
            }
            set
            {
                OnHaveChanging(value);
                ReportPropertyChanging("Have");
                _Have = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Have");
                OnHaveChanged();
            }
        }
        private global::System.Boolean _Have;
        partial void OnHaveChanging(global::System.Boolean value);
        partial void OnHaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BoxTitle
        {
            get
            {
                return _BoxTitle;
            }
            set
            {
                OnBoxTitleChanging(value);
                ReportPropertyChanging("BoxTitle");
                _BoxTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BoxTitle");
                OnBoxTitleChanged();
            }
        }
        private global::System.String _BoxTitle;
        partial void OnBoxTitleChanging(global::System.String value);
        partial void OnBoxTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiskNumber
        {
            get
            {
                return _DiskNumber;
            }
            set
            {
                OnDiskNumberChanging(value);
                ReportPropertyChanging("DiskNumber");
                _DiskNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiskNumber");
                OnDiskNumberChanged();
            }
        }
        private global::System.String _DiskNumber;
        partial void OnDiskNumberChanging(global::System.String value);
        partial void OnDiskNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MediaCollectionModel", "FK_Media_MediaTypes1", "MediaType")]
        public MediaType MediaType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MediaType>("MediaCollectionModel.FK_Media_MediaTypes1", "MediaType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MediaType>("MediaCollectionModel.FK_Media_MediaTypes1", "MediaType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MediaType> MediaTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MediaType>("MediaCollectionModel.FK_Media_MediaTypes1", "MediaType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MediaType>("MediaCollectionModel.FK_Media_MediaTypes1", "MediaType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MediaCollectionModel", "GenreMedia", "Genre")]
        public EntityCollection<Genre> Genres
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Genre>("MediaCollectionModel.GenreMedia", "Genre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Genre>("MediaCollectionModel.GenreMedia", "Genre", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
