<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.5.1" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <ProjectReference Include="..\OoBDev.Plugins.Packaging\OoBDev.Plugins.Packaging.csproj" />
    <ProjectReference Include="..\OoBDev.Plugins.Launchers.Plain\OoBDev.Plugins.Launchers.Plain.csproj" />
    <ProjectReference Include="..\OoBDev.Plugins.TestKit\OoBDev.Plugins.TestKit.csproj" />
    <Using Include="OoBDev.Plugins.TestKit" />
  </ItemGroup>
</Project>
