ALTER TABLE [dbo].[ContentMetaData]
    ADD CONSTRAINT [PK_ContentMetaData] PRIMARY KEY NONCLUSTERED ([ContentMetaID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

