/*ALTER TABLE [dbo].[ContentFrames]
    ADD CONSTRAINT [UQ_ContentFrame_RowID] UNIQUE NONCLUSTERED ([RowID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];*/

