ALTER TABLE [dbo].[Groups]
    ADD CONSTRAINT [PK_Groups] PRIMARY KEY NONCLUSTERED ([GroupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

