ALTER TABLE [dbo].[Priorities]
    ADD CONSTRAINT [PK_Table_1] PRIMARY KEY NONCLUSTERED ([PriorityID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];



