ALTER TABLE [dbo].[TaskTypes]
    ADD CONSTRAINT [PK_TaskTypes] PRIMARY KEY CLUSTERED ([TaskTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

