//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.Service.Callbacks.ConnectionRelayServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.whited.us/2008/01/RelayService", ConfigurationName="ConnectionRelayServer.NetworkRelay", CallbackContract=typeof(Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelayCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface NetworkRelay {
        
        // CODEGEN: Parameter 'server' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/Connect")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void Connect(Monitor.Service.Callbacks.ConnectionRelayServer.Connect request);
        
        // CODEGEN: Generating message contract since the wrapper name (DataMessage) of message DataMessage does not match the default value (SendData)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/SendData")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SendData(Monitor.Service.Callbacks.ConnectionRelayServer.DataMessage request);
        
        // CODEGEN: Generating message contract since the operation SendSystemEvent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/SendSystemEvent", ReplyAction="http://www.whited.us/2008/01/RelayService/NetworkRelay/SendSystemEventResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Monitor.Service.Callbacks.ConnectionRelayServer.SendSystemEventResponse SendSystemEvent(Monitor.Service.Callbacks.ConnectionRelayServer.EventMessage request);
        
        // CODEGEN: Parameter 'inboundMessage' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/LoopbackWithCallBack")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void LoopbackWithCallBack(Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackWithCallBack request);
        
        // CODEGEN: Parameter 'LoopbackResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/Loopback", ReplyAction="http://www.whited.us/2008/01/RelayService/NetworkRelay/LoopbackResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackResponse Loopback(Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/Disconnect")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void Disconnect();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NetworkRelayCallback {
        
        // CODEGEN: Generating message contract since the wrapper name (DataMessage) of message DataMessage does not match the default value (SendData)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/SendData")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SendData(Monitor.Service.Callbacks.ConnectionRelayServer.DataMessage request);
        
        // CODEGEN: Generating message contract since the operation CallbackSystemEvent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/CallbackSystemEvent", ReplyAction="http://www.whited.us/2008/01/RelayService/NetworkRelay/CallbackSystemEventRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Monitor.Service.Callbacks.ConnectionRelayServer.CallbackSystemEventResponse CallbackSystemEvent(Monitor.Service.Callbacks.ConnectionRelayServer.EventMessage request);
        
        // CODEGEN: Parameter 'originSocketName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.whited.us/2008/01/RelayService/NetworkRelay/ReturnLoopBack")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ReturnLoopBack(Monitor.Service.Callbacks.ConnectionRelayServer.ReturnLoopBack request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Connect", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class Connect {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string server;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=1)]
        public int port;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orgSocket;
        
        public Connect() {
        }
        
        public Connect(string server, int port, string orgSocket) {
            this.server = server;
            this.port = port;
            this.orgSocket = orgSocket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataMessage", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class DataMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.whited.us/2008/01/RelayService")]
        public int DataPacketSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.whited.us/2008/01/RelayService")]
        public int SequenceNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] DataPacket;
        
        public DataMessage() {
        }
        
        public DataMessage(int DataPacketSize, int SequenceNumber, byte[] DataPacket) {
            this.DataPacketSize = DataPacketSize;
            this.SequenceNumber = SequenceNumber;
            this.DataPacket = DataPacket;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WhitedUS.Services.NetworkRelay")]
    public enum EventType {
        
        /// <remarks/>
        SocketHangup,
        
        /// <remarks/>
        ResendRequest,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventMessage", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class EventMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.whited.us/2008/01/RelayService")]
        public Monitor.Service.Callbacks.ConnectionRelayServer.EventType EventType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Payload;
        
        public EventMessage() {
        }
        
        public EventMessage(Monitor.Service.Callbacks.ConnectionRelayServer.EventType EventType, byte[] Payload) {
            this.EventType = EventType;
            this.Payload = Payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSystemEventResponse {
        
        public SendSystemEventResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoopbackWithCallBack", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class LoopbackWithCallBack {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inboundMessage;
        
        public LoopbackWithCallBack() {
        }
        
        public LoopbackWithCallBack(string inboundMessage) {
            this.inboundMessage = inboundMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Loopback", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class LoopbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inboundMessage;
        
        public LoopbackRequest() {
        }
        
        public LoopbackRequest(string inboundMessage) {
            this.inboundMessage = inboundMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoopbackResponse", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class LoopbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoopbackResult;
        
        public LoopbackResponse() {
        }
        
        public LoopbackResponse(string LoopbackResult) {
            this.LoopbackResult = LoopbackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallbackSystemEventResponse {
        
        public CallbackSystemEventResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnLoopBack", WrapperNamespace="http://www.whited.us/2008/01/RelayService", IsWrapped=true)]
    public partial class ReturnLoopBack {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string originSocketName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.whited.us/2008/01/RelayService", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OutboundData;
        
        public ReturnLoopBack() {
        }
        
        public ReturnLoopBack(string originSocketName, string OutboundData) {
            this.originSocketName = originSocketName;
            this.OutboundData = OutboundData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NetworkRelayChannel : Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NetworkRelayClient : System.ServiceModel.DuplexClientBase<Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay>, Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay {
        
        public NetworkRelayClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public NetworkRelayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public NetworkRelayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NetworkRelayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NetworkRelayClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay.Connect(Monitor.Service.Callbacks.ConnectionRelayServer.Connect request) {
            base.Channel.Connect(request);
        }
        
        public void Connect(string server, int port, string orgSocket) {
            Monitor.Service.Callbacks.ConnectionRelayServer.Connect inValue = new Monitor.Service.Callbacks.ConnectionRelayServer.Connect();
            inValue.server = server;
            inValue.port = port;
            inValue.orgSocket = orgSocket;
            ((Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay)(this)).Connect(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay.SendData(Monitor.Service.Callbacks.ConnectionRelayServer.DataMessage request) {
            base.Channel.SendData(request);
        }
        
        public void SendData(int DataPacketSize, int SequenceNumber, byte[] DataPacket) {
            Monitor.Service.Callbacks.ConnectionRelayServer.DataMessage inValue = new Monitor.Service.Callbacks.ConnectionRelayServer.DataMessage();
            inValue.DataPacketSize = DataPacketSize;
            inValue.SequenceNumber = SequenceNumber;
            inValue.DataPacket = DataPacket;
            ((Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay)(this)).SendData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor.Service.Callbacks.ConnectionRelayServer.SendSystemEventResponse Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay.SendSystemEvent(Monitor.Service.Callbacks.ConnectionRelayServer.EventMessage request) {
            return base.Channel.SendSystemEvent(request);
        }
        
        public void SendSystemEvent(Monitor.Service.Callbacks.ConnectionRelayServer.EventType EventType, byte[] Payload) {
            Monitor.Service.Callbacks.ConnectionRelayServer.EventMessage inValue = new Monitor.Service.Callbacks.ConnectionRelayServer.EventMessage();
            inValue.EventType = EventType;
            inValue.Payload = Payload;
            Monitor.Service.Callbacks.ConnectionRelayServer.SendSystemEventResponse retVal = ((Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay)(this)).SendSystemEvent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay.LoopbackWithCallBack(Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackWithCallBack request) {
            base.Channel.LoopbackWithCallBack(request);
        }
        
        public void LoopbackWithCallBack(string inboundMessage) {
            Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackWithCallBack inValue = new Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackWithCallBack();
            inValue.inboundMessage = inboundMessage;
            ((Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay)(this)).LoopbackWithCallBack(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackResponse Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay.Loopback(Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackRequest request) {
            return base.Channel.Loopback(request);
        }
        
        public string Loopback(string inboundMessage) {
            Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackRequest inValue = new Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackRequest();
            inValue.inboundMessage = inboundMessage;
            Monitor.Service.Callbacks.ConnectionRelayServer.LoopbackResponse retVal = ((Monitor.Service.Callbacks.ConnectionRelayServer.NetworkRelay)(this)).Loopback(inValue);
            return retVal.LoopbackResult;
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
    }
}
